//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADUserSyncFilter
    {
        public System.Guid ADUserSyncFilterID { get; set; }
        public int ADUserSyncFilterIndex { get; set; }
        public System.Guid ADUserSyncDetail { get; set; }
        public System.Guid PropertyName { get; set; }
        public string PropertyValue { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual ADUserSyncDetail ADUserSyncDetail1 { get; set; }
        public virtual NxSyncField NxSyncField { get; set; }
    }
}
