//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADUserSyncResultsDetailReport
    {
        public System.Guid ADUserSyncResultsDetailReportID { get; set; }
        public int ADUserSyncResultsDetailReportIndex { get; set; }
        public int ADUserSyncResultsReport { get; set; }
        public System.Guid ADUserSyncDetail { get; set; }
        public System.Guid ActiveDirectoryID { get; set; }
        public string ActiveDirectoryName { get; set; }
        public string ActiveDirectoryNetworkAlias { get; set; }
        public byte IsOverlapping { get; set; }
        public int SyncStatus { get; set; }
        public int SyncStatusNxUser { get; set; }
        public int SyncStatusEntityPerson { get; set; }
        public byte IsNew { get; set; }
        public byte IsNewNxUser { get; set; }
        public byte IsNewEntityPerson { get; set; }
        public string ExceptionMessages { get; set; }
        public string ExceptionMessages_UnformattedText { get; set; }
        public string ExceptionMessagesNxUser { get; set; }
        public string ExceptionMessagesNxUser_UnformattedText { get; set; }
        public string ExceptionMessagesEntityPerson { get; set; }
        public string ExceptionMessagesEntityPerson_UnformattedText { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
