//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class APTranAcctMask
    {
        public System.Guid APTranAcctMaskID { get; set; }
        public string APTranType { get; set; }
        public string APTranDetailList { get; set; }
        public Nullable<int> GLAcctMask { get; set; }
        public string Flag1099 { get; set; }
        public byte IsVchrPost { get; set; }
        public byte IsCkPost { get; set; }
        public string SortString { get; set; }
        public string Description { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
