//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVRReportInstance
    {
        public System.Guid AVRReportInstanceID { get; set; }
        public int ReportInstanceIndex { get; set; }
        public string InstanceName { get; set; }
        public string InstanceDescription { get; set; }
        public int AVRReportCatalog { get; set; }
        public Nullable<byte> IsGlobal { get; set; }
        public Nullable<System.Guid> AVRPublicDistributionList { get; set; }
        public Nullable<System.Guid> NxNtfEvent { get; set; }
        public Nullable<int> TreeNodeSetup { get; set; }
        public string AVRReportDistributionQuery { get; set; }
        public string SelectQuery { get; set; }
        public byte IsActive { get; set; }
        public string JoinSelectedPath { get; set; }
        public string DistributionXOQL { get; set; }
        public string SelectQueryText { get; set; }
    
        public virtual AVRPublicDistributionList AVRPublicDistributionList1 { get; set; }
        public virtual NxNtfEvent NxNtfEvent1 { get; set; }
    }
}
