//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAcctTrust
    {
        public System.Guid BankAcctTrustID { get; set; }
        public Nullable<int> DedicatedMatter { get; set; }
        public Nullable<int> RelatedBankAcct { get; set; }
        public Nullable<System.Guid> ReceiptPrnTemplate { get; set; }
        public Nullable<System.Guid> CheckPrnTemplate { get; set; }
        public string GLType { get; set; }
        public int ContraGLAcct { get; set; }
        public Nullable<int> DisbGLAcct { get; set; }
        public Nullable<int> Site { get; set; }
        public string TrustInterestType { get; set; }
        public string LastReceiptNum { get; set; }
        public string LastTransferNum { get; set; }
        public string LastCheckNum { get; set; }
        public string LastDisburseNum { get; set; }
        public string LastAdjustNum { get; set; }
        public Nullable<byte> IsControlled { get; set; }
        public Nullable<decimal> CnltAmount { get; set; }
        public string CnltCurrency { get; set; }
        public Nullable<decimal> CnltIntRate { get; set; }
        public Nullable<System.DateTime> CntInvDate { get; set; }
        public Nullable<int> BeneficiaryEntity { get; set; }
        public Nullable<int> BeneficiarySite { get; set; }
        public Nullable<int> TransferToAcct { get; set; }
        public Nullable<byte> IsTransferOnly { get; set; }
        public Nullable<int> AutoDisbPayee { get; set; }
        public string AutoTrustDisbmtType { get; set; }
        public string AutoIntendedUse { get; set; }
        public string Narrative { get; set; }
        public string Narrative_UnformattedText { get; set; }
        public string Country { get; set; }
        public string TrustAcctMoneyList { get; set; }
        public string BSBNumber { get; set; }
        public Nullable<int> Donor { get; set; }
        public Nullable<int> DonorSite { get; set; }
        public string PowerDate { get; set; }
        public string DeceasedName { get; set; }
        public Nullable<System.DateTime> DeceasedDate { get; set; }
        public byte IsRequireReceiptDetail { get; set; }
        public byte IsRequirePrintReceipt { get; set; }
        public byte IsInvestment { get; set; }
        public string NextReceiptNumNoCM { get; set; }
        public Nullable<System.Guid> ElecRemittanceTemplate { get; set; }
        public string LastEFTNum { get; set; }
        public string NextEFTNum { get; set; }
        public string DMK_RcptType { get; set; }
        public Nullable<System.Guid> AnchorMask { get; set; }
    
        public virtual BaseGLSegment BaseGLSegment { get; set; }
        public virtual NxPrinterTemplate NxPrinterTemplate { get; set; }
        public virtual NxPrinterTemplate NxPrinterTemplate1 { get; set; }
        public virtual NxPrinterTemplate NxPrinterTemplate2 { get; set; }
    }
}
