//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAcctCk
    {
        public System.Guid BankAcctCkID { get; set; }
        public int BankAcctAP { get; set; }
        public string CkTypeList { get; set; }
        public byte IsAutoNumCk { get; set; }
        public string LastCk { get; set; }
        public byte IsEFT { get; set; }
        public Nullable<System.Guid> NxPrinterTemplate { get; set; }
        public Nullable<System.Guid> RemittanceTemplate { get; set; }
        public string RemittanceEmailFromAddr { get; set; }
        public string RemittanceEmailSubj { get; set; }
        public Nullable<System.Guid> ElecRemittanceTemplate { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual NxPrinterTemplate NxPrinterTemplate1 { get; set; }
        public virtual NxPrinterTemplate NxPrinterTemplate2 { get; set; }
        public virtual NxPrinterTemplate NxPrinterTemplate3 { get; set; }
    }
}
