//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankRecTranDate
    {
        public System.Guid BankRecTranDateID { get; set; }
        public int BankAcct { get; set; }
        public int BankStmt { get; set; }
        public string GLBook { get; set; }
    }
}
