//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankRecTranDateRun
    {
        public System.Guid BankRecTranDateRunID { get; set; }
        public Nullable<int> BankAcct { get; set; }
        public Nullable<int> BankStmt { get; set; }
        public string GLBook { get; set; }
        public string BankAcctDesc { get; set; }
        public string BankStmtDesc { get; set; }
        public string GLBookDesc { get; set; }
    }
}
