//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseGLSegment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaseGLSegment()
        {
            this.BankAcctTrusts = new HashSet<BankAcctTrust>();
            this.BasePosts = new HashSet<BasePost>();
            this.ChrgTypeAdditionalPosts = new HashSet<ChrgTypeAdditionalPost>();
            this.CostTypeAdditionalPosts = new HashSet<CostTypeAdditionalPost>();
            this.GLMaskVars = new HashSet<GLMaskVar>();
            this.GLRollups = new HashSet<GLRollup>();
            this.PurgeTypePosts = new HashSet<PurgeTypePost>();
            this.ReceiptTypeAdditionalPosts = new HashSet<ReceiptTypeAdditionalPost>();
            this.TimeTypeAdditionalPosts = new HashSet<TimeTypeAdditionalPost>();
            this.TranTypeAdditionalPosts = new HashSet<TranTypeAdditionalPost>();
            this.TranTypeStdPosts = new HashSet<TranTypeStdPost>();
            this.TranTypeStdPosts1 = new HashSet<TranTypeStdPost>();
            this.TranTypeStdPosts2 = new HashSet<TranTypeStdPost>();
            this.TranTypeStdPosts3 = new HashSet<TranTypeStdPost>();
            this.UnalTypeAdditionalPosts = new HashSet<UnalTypeAdditionalPost>();
            this.UnalTypePosts = new HashSet<UnalTypePost>();
            this.WPControls = new HashSet<WPControl>();
        }
    
        public System.Guid BaseGLSegmentID { get; set; }
        public string SegValTypeList { get; set; }
        public string GLGroup1 { get; set; }
        public string GLGroup2 { get; set; }
        public string GLGroup3 { get; set; }
        public string BaseGLValue { get; set; }
        public string BaseGLDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankAcctTrust> BankAcctTrusts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasePost> BasePosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChrgTypeAdditionalPost> ChrgTypeAdditionalPosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostTypeAdditionalPost> CostTypeAdditionalPosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GLMaskVar> GLMaskVars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GLRollup> GLRollups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurgeTypePost> PurgeTypePosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptTypeAdditionalPost> ReceiptTypeAdditionalPosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTypeAdditionalPost> TimeTypeAdditionalPosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TranTypeAdditionalPost> TranTypeAdditionalPosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TranTypeStdPost> TranTypeStdPosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TranTypeStdPost> TranTypeStdPosts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TranTypeStdPost> TranTypeStdPosts2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TranTypeStdPost> TranTypeStdPosts3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnalTypeAdditionalPost> UnalTypeAdditionalPosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnalTypePost> UnalTypePosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WPControl> WPControls { get; set; }
    }
}
