//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiztalkExport
    {
        public System.Guid BiztalkExportID { get; set; }
        public string WebServiceURL { get; set; }
        public Nullable<System.Guid> BizTalkExportType { get; set; }
        public string TriggerFileName { get; set; }
        public Nullable<byte> StockConfigItem { get; set; }
    
        public virtual NxIntegrationExportType NxIntegrationExportType { get; set; }
    }
}
