//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashSourceList
    {
        public System.Guid CashSourceListID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string SortString { get; set; }
        public byte IsRcpt { get; set; }
        public byte IsAPCk { get; set; }
        public byte IsGJ { get; set; }
        public byte IsTrustRcpt { get; set; }
        public byte IsTrustCk { get; set; }
        public byte IsTrustTrsf { get; set; }
        public byte IsTrustAdj { get; set; }
        public byte IsReversed { get; set; }
        public byte IsCash { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
