//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cft3TierSFHits
    {
        public System.Guid Cft3TierSFHitsID { get; set; }
        public string WhereFound { get; set; }
        public string Text { get; set; }
        public string Text_UnformattedText { get; set; }
        public Nullable<int> ClientIndex { get; set; }
        public Nullable<int> MatterIndex { get; set; }
        public Nullable<int> EntityIndex { get; set; }
        public string FoundItemID { get; set; }
        public Nullable<System.Guid> Cft3TierNxItem { get; set; }
        public string HitType { get; set; }
        public string ArchCode { get; set; }
        public Nullable<System.Guid> ResultID { get; set; }
    }
}
