//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cft3TierBasicGenDtl
    {
        public System.Guid Cft3TierBasicGenDtlID { get; set; }
        public string Caption { get; set; }
        public string Value { get; set; }
        public string FoundItemID { get; set; }
        public Nullable<System.Guid> Cft3TierNxItem { get; set; }
        public Nullable<System.Guid> CftSearchResultGen { get; set; }
    }
}
