//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cft3TierSummarySearchFields
    {
        public System.Guid Cft3TierSummarySearchFieldsID { get; set; }
        public string SearchFields { get; set; }
        public string PhoneticSearch { get; set; }
        public Nullable<System.Guid> SearchFieldID { get; set; }
        public Nullable<System.Guid> Cft3TierNxItem { get; set; }
    }
}
