//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cft3TierDetailRPDtl
    {
        public System.Guid Cft3TierDetailRPDtlID { get; set; }
        public string EntityName { get; set; }
        public string Type { get; set; }
        public string RPStatus { get; set; }
        public string Role { get; set; }
        public string Relationship { get; set; }
        public string Narrative { get; set; }
        public string Narrative_UnformattedText { get; set; }
        public Nullable<int> MatterIndex { get; set; }
        public Nullable<int> ClientIndex { get; set; }
        public Nullable<System.Guid> Cft3TierNxItem { get; set; }
        public Nullable<int> EntityIndex { get; set; }
        public string RPType { get; set; }
    }
}
