//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cft3TierNxItem
    {
        public System.Guid Cft3TierNxItemID { get; set; }
        public Nullable<System.Guid> SearchID { get; set; }
        public System.Guid ReportID { get; set; }
        public string TypeOfSearch { get; set; }
        public Nullable<byte> BasicSelection { get; set; }
        public Nullable<byte> DetailSection { get; set; }
        public Nullable<byte> SummarySection { get; set; }
    }
}
