//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cft3TierSummarySearchTerm
    {
        public System.Guid Cft3TierSummarySearchTermID { get; set; }
        public string SearchName { get; set; }
        public string PhoneticSearch { get; set; }
        public Nullable<System.Guid> SearchTermID { get; set; }
        public Nullable<System.Guid> Cft3TierNxItem { get; set; }
        public string ResultsCount { get; set; }
        public string SearchTerm { get; set; }
        public string SearchTerms { get; set; }
    }
}
