//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cft3TierBasicEntityClass
    {
        public System.Guid Cft3TierBasicEntityClassID { get; set; }
        public Nullable<System.Guid> CftEntityClass { get; set; }
        public string ClassIndex { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> Cft3TierNxItem { get; set; }
        public Nullable<int> EntityIndex { get; set; }
        public Nullable<byte> IsOtherEntityClass { get; set; }
        public string RMImages { get; set; }
    
        public virtual CftEntityClass CftEntityClass1 { get; set; }
    }
}
