//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class CftNewBizRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CftNewBizRequest()
        {
            this.CftDCSSearches = new HashSet<CftDCSSearch>();
            this.cftEmailHistories = new HashSet<cftEmailHistory>();
            this.CftEmailReassignNotifications = new HashSet<CftEmailReassignNotification>();
            this.CftNewBizFilters = new HashSet<CftNewBizFilter>();
            this.CftNewBizSearchNames = new HashSet<CftNewBizSearchName>();
            this.CftRelatedParties = new HashSet<CftRelatedParty>();
            this.CftSearches = new HashSet<CftSearch>();
            this.CftSearchComments = new HashSet<CftSearchComment>();
            this.CftSelResultsMains = new HashSet<CftSelResultsMain>();
            this.CftWorkflowTrackings = new HashSet<CftWorkflowTracking>();
        }
    
        public System.Guid CftNewBizRequestID { get; set; }
        public string CftSearchReason { get; set; }
        public Nullable<int> Client { get; set; }
        public Nullable<int> Matter { get; set; }
        public Nullable<int> Entity { get; set; }
        public System.DateTime RequestDateTime { get; set; }
        public int JobNumber { get; set; }
        public string Description { get; set; }
        public Nullable<byte> IsCreatedMatter { get; set; }
        public Nullable<byte> IsCreatedClient { get; set; }
        public string CftNBRStatus { get; set; }
        public string CurrentWorkflowStep { get; set; }
        public string OrgProc { get; set; }
        public Nullable<System.Guid> ClientSearchNameId { get; set; }
        public System.Guid Submitter { get; set; }
        public string FinalizeResult { get; set; }
        public Nullable<System.Guid> RouteTo { get; set; }
        public Nullable<System.DateTime> DateRouted { get; set; }
        public Nullable<System.DateTime> DateDecided { get; set; }
        public string DeclineReason { get; set; }
        public string DeclineComment { get; set; }
        public Nullable<System.Guid> DecidedBy { get; set; }
        public Nullable<System.Guid> CftSearchAuthority { get; set; }
        public string LoadNumber { get; set; }
        public string LoadSource { get; set; }
        public string LoadGroup { get; set; }
        public string LoadBatchID { get; set; }
        public Nullable<byte> LoadFlag { get; set; }
        public Nullable<System.Guid> LastEditedBy { get; set; }
        public Nullable<byte> FromCMCase { get; set; }
        public Nullable<int> CmCase { get; set; }
        public string CftResultView { get; set; }
        public string AdminComments { get; set; }
        public string AdminComments_UnformattedText { get; set; }
        public Nullable<System.Guid> ClientMatterCreationRouteTo { get; set; }
        public Nullable<byte> IsNoSearchNecessary { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CftDCSSearch> CftDCSSearches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cftEmailHistory> cftEmailHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CftEmailReassignNotification> CftEmailReassignNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CftNewBizFilter> CftNewBizFilters { get; set; }
        public virtual CftSearchAuthority CftSearchAuthority1 { get; set; }
        public virtual NxBaseUser NxBaseUser { get; set; }
        public virtual NxUser NxUser { get; set; }
        public virtual NxUser NxUser1 { get; set; }
        public virtual NxUser NxUser2 { get; set; }
        public virtual NxUser NxUser3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CftNewBizSearchName> CftNewBizSearchNames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CftRelatedParty> CftRelatedParties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CftSearch> CftSearches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CftSearchComment> CftSearchComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CftSelResultsMain> CftSelResultsMains { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CftWorkflowTracking> CftWorkflowTrackings { get; set; }
    }
}
