//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class CftSaveCopyResultEntityRP
    {
        public System.Guid CftSaveCopyResultEntityRPID { get; set; }
        public System.Guid CftRelatedPartyID { get; set; }
        public string LinkType { get; set; }
        public string RPStatus { get; set; }
        public string ClientStatus { get; set; }
        public string MatterStatus { get; set; }
        public string Notes { get; set; }
        public string Notes_UnformattedText { get; set; }
        public int CftSaveCopyResultEntityRPIndex { get; set; }
    }
}
