//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class CftSelResultDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CftSelResultDetail()
        {
            this.CftSelResultsDetailComments = new HashSet<CftSelResultsDetailComment>();
            this.CftSelSearchResultComments = new HashSet<CftSelSearchResultComment>();
        }
    
        public System.Guid CftSelResultDetailsID { get; set; }
        public string Name { get; set; }
        public string GroupingLabel { get; set; }
        public string WhereFound { get; set; }
        public string Text { get; set; }
        public string WhereFoundArchCode { get; set; }
        public string WhereFoundItemId { get; set; }
        public Nullable<System.Guid> DetailItemID { get; set; }
        public Nullable<System.Guid> CftSelResultMain { get; set; }
        public int CftSelResultDetailsIndex { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual CftSelResultsMain CftSelResultsMain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CftSelResultsDetailComment> CftSelResultsDetailComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CftSelSearchResultComment> CftSelSearchResultComments { get; set; }
    }
}
