//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class CftSaveCopyResultEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CftSaveCopyResultEntity()
        {
            this.CftSaveCopyResultClientLinks = new HashSet<CftSaveCopyResultClientLink>();
            this.CftSaveCopyResultMatterLinks = new HashSet<CftSaveCopyResultMatterLink>();
            this.CftSaveCopyResultProspectLinks = new HashSet<CftSaveCopyResultProspectLink>();
        }
    
        public System.Guid CftSaveCopyResultEntityID { get; set; }
        public string SubClass { get; set; }
        public string Type { get; set; }
        public Nullable<int> PayorIndex { get; set; }
        public Nullable<int> PayeeIndex { get; set; }
        public Nullable<int> VendorIndex { get; set; }
        public Nullable<int> BankIndex { get; set; }
        public Nullable<int> TimekeeperIndex { get; set; }
        public Nullable<System.Guid> CollectorID { get; set; }
        public Nullable<System.Guid> WriteOffApproverID { get; set; }
        public int CftSaveCopyResultEntityIndex { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CftSaveCopyResultClientLink> CftSaveCopyResultClientLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CftSaveCopyResultMatterLink> CftSaveCopyResultMatterLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CftSaveCopyResultProspectLink> CftSaveCopyResultProspectLinks { get; set; }
    }
}
