//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class CftSaveCopySearchResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CftSaveCopySearchResult()
        {
            this.CftSaveCopyResultRPs = new HashSet<CftSaveCopyResultRP>();
        }
    
        public System.Guid CftSaveCopySearchResultID { get; set; }
        public int CftSaveCopySearch { get; set; }
        public Nullable<System.Guid> CftSaveCopySearchTerm { get; set; }
        public string SearchTermGroupingLabel { get; set; }
        public string Text { get; set; }
        public string Role { get; set; }
        public string Relationship { get; set; }
        public Nullable<int> EntityIndex { get; set; }
        public string EntityName { get; set; }
        public Nullable<int> ClientIndex { get; set; }
        public string ClientNumber { get; set; }
        public string ClientName { get; set; }
        public Nullable<int> MatterIndex { get; set; }
        public string MatterNumber { get; set; }
        public string MatterName { get; set; }
        public System.Guid FullTextDocumentID { get; set; }
        public int HitCount { get; set; }
        public int TextLanguage { get; set; }
        public string DataItemID { get; set; }
        public string ArchCode { get; set; }
        public string PartialText { get; set; }
        public int WhereFoundSortOrder { get; set; }
        public string StatusSortString { get; set; }
        public string WhereFoundArchCode { get; set; }
        public string WhereFoundAttrCode { get; set; }
        public string WhereFoundArchCaption { get; set; }
        public string WhereFoundAttrCaption { get; set; }
        public string WhereFoundItemID { get; set; }
        public int CftQuickClearImages { get; set; }
        public Nullable<int> CorporateTreeImage { get; set; }
        public int SearchTermSortOrder { get; set; }
        public System.Guid DetailItemID { get; set; }
        public string DetailArchCode { get; set; }
        public Nullable<System.Guid> WhereFoundFrameworkItemID { get; set; }
        public byte IsFiltered { get; set; }
        public byte IsSelected { get; set; }
        public string EntitySanction { get; set; }
        public string CftSearchCompareStatus { get; set; }
        public string SourceCollection { get; set; }
        public byte IsExternalHit { get; set; }
        public string FTXSourceType { get; set; }
        public int CftSaveCopySearchResultIndex { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<System.Guid> CftSearchResult { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CftSaveCopyResultRP> CftSaveCopyResultRPs { get; set; }
    }
}
