//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChrgBillTax
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChrgBillTax()
        {
            this.ChrgBillTaxPmts = new HashSet<ChrgBillTaxPmt>();
        }
    
        public System.Guid ChrgBillTaxID { get; set; }
        public int ChrgBillPar { get; set; }
        public Nullable<int> TimeBill { get; set; }
        public Nullable<int> CostBill { get; set; }
        public Nullable<int> ChrgBill { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> CurrDate { get; set; }
        public decimal ChrgAmt { get; set; }
        public decimal ChrgBal { get; set; }
        public Nullable<int> ARDetail { get; set; }
        public Nullable<decimal> SourceAmt { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChrgBillTaxPmt> ChrgBillTaxPmts { get; set; }
    }
}
