//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class CkSelParameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CkSelParameter()
        {
            this.CkSelParameterDetails = new HashSet<CkSelParameterDetail>();
            this.CkSelParameterUnavails = new HashSet<CkSelParameterUnavail>();
        }
    
        public System.Guid CkSelParametersID { get; set; }
        public string Description { get; set; }
        public int BankAcct { get; set; }
        public string Currency { get; set; }
        public byte IsInterCurr { get; set; }
        public string CurrType { get; set; }
        public byte IsElectronicPay { get; set; }
        public byte IsSameDay { get; set; }
        public byte IsAdvice { get; set; }
        public string CkSelOQL { get; set; }
        public string CkSelText { get; set; }
        public string SortString { get; set; }
        public Nullable<byte> IsClientPartialPay { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<byte> IsClientFullPay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CkSelParameterDetail> CkSelParameterDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CkSelParameterUnavail> CkSelParameterUnavails { get; set; }
    }
}
