//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class CkSelVchrDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CkSelVchrDetail()
        {
            this.CkDetails = new HashSet<CkDetail>();
        }
    
        public System.Guid CkSelVchrDetailID { get; set; }
        public System.Guid CkSelVchr { get; set; }
        public System.Guid VchrDetail { get; set; }
        public string Currency { get; set; }
        public System.DateTime CurrDate { get; set; }
        public decimal VchrAmt { get; set; }
        public decimal PayAmt { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CkDetail> CkDetails { get; set; }
        public virtual CkSelVchr CkSelVchr1 { get; set; }
        public virtual VchrDetail VchrDetail1 { get; set; }
    }
}
