//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class CkSel
    {
        public System.Guid CkSelID { get; set; }
        public int BankAcctAP { get; set; }
        public System.DateTime CkDate { get; set; }
        public string CkSelStatusList { get; set; }
        public byte IsElectronicPay { get; set; }
        public byte IsSameDay { get; set; }
        public byte IsAdvice { get; set; }
        public string Currency { get; set; }
        public byte IsMultCurr { get; set; }
        public string CkSelOQL { get; set; }
        public string CkSelText { get; set; }
        public int CkSelIndex { get; set; }
        public string CurrType { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<System.Guid> NxUser { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual NxUser NxUser1 { get; set; }
    }
}
