//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class CliDate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CliDate()
        {
            this.BalHistARs = new HashSet<BalHistAR>();
            this.BalHistWIPs = new HashSet<BalHistWIP>();
            this.CliOrgTkprs = new HashSet<CliOrgTkpr>();
            this.CliPlfrTkprs = new HashSet<CliPlfrTkpr>();
        }
    
        public System.Guid CliDateID { get; set; }
        public Nullable<int> ClientLkUp { get; set; }
        public System.DateTime EffStart { get; set; }
        public string Office { get; set; }
        public string TkprTeam { get; set; }
        public string Arrangement { get; set; }
        public int RspTkpr { get; set; }
        public int BillTkpr { get; set; }
        public int SpvTkpr { get; set; }
        public Nullable<System.DateTime> NxEndDate { get; set; }
        public Nullable<System.DateTime> NxStartDate { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BalHistAR> BalHistARs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BalHistWIP> BalHistWIPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CliOrgTkpr> CliOrgTkprs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CliPlfrTkpr> CliPlfrTkprs { get; set; }
    }
}
