//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientInfoExtractRunEvent
    {
        public System.Guid ClientInfoExtractRunEventID { get; set; }
        public System.Guid ClientInfoExtractRun { get; set; }
    
        public virtual ClientInfoExtractRun ClientInfoExtractRun1 { get; set; }
    }
}
