//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientInfoReceive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientInfoReceive()
        {
            this.ClientInfoReceiveResultDetails = new HashSet<ClientInfoReceiveResultDetail>();
        }
    
        public System.Guid ClientInfoReceiveID { get; set; }
        public string ExtractName { get; set; }
        public string Description { get; set; }
        public string SQL { get; set; }
        public Nullable<System.Guid> ReceiveRun { get; set; }
        public string Result { get; set; }
        public string Category { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual ClientInfoReceiveRun ClientInfoReceiveRun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientInfoReceiveResultDetail> ClientInfoReceiveResultDetails { get; set; }
    }
}
