//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class CmCase
    {
        public System.Guid CmCaseID { get; set; }
        public int CmCaseIndex { get; set; }
        public int CmMatter { get; set; }
        public string CmCaseNumber { get; set; }
        public string Description { get; set; }
        public string DocketID { get; set; }
        public Nullable<int> Language { get; set; }
        public string CmCaseCategory { get; set; }
        public Nullable<System.Guid> CmTimeZone { get; set; }
        public Nullable<System.Guid> CmRuleset { get; set; }
        public Nullable<System.Guid> CmJurisdiction { get; set; }
        public string Alert { get; set; }
        public Nullable<int> RMSubmatter { get; set; }
        public string Narrative { get; set; }
        public string Narrative_UnformattedText { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
