//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class CmCaseStatusList
    {
        public System.Guid CmCaseStatusListID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public byte IsDefault { get; set; }
        public byte IsSimpleMaint { get; set; }
        public byte IsDocketMaint { get; set; }
        public byte IsModifyCase { get; set; }
    }
}
