//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class CmDivorce
    {
        public System.Guid CmDivorceID { get; set; }
        public int CmDivorceIndex { get; set; }
        public string Assets { get; set; }
        public string Assets_UnformattedText { get; set; }
        public string PrenupDtls { get; set; }
        public string PrenupDtls_UnformattedText { get; set; }
    }
}
