//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class CmManualReschedDet
    {
        public System.Guid CmManualReschedDetID { get; set; }
        public Nullable<byte> AllDayEvent { get; set; }
        public Nullable<System.DateTime> CompleteDateTime { get; set; }
        public Nullable<byte> IsSelect { get; set; }
        public string Narrative { get; set; }
        public string Narrative_UnformattedText { get; set; }
        public Nullable<System.DateTime> RelevantDate { get; set; }
        public string Subject { get; set; }
        public Nullable<System.Guid> CmEventCode { get; set; }
        public Nullable<int> CmEventPriorityList { get; set; }
        public Nullable<System.Guid> CmManualResched { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual CmManualResched CmManualResched1 { get; set; }
    }
}
