//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class CmMCPercentCompResult
    {
        public System.Guid CmMCPercentCompResultsID { get; set; }
        public int CmMCPercentCompResultsIndex { get; set; }
        public int CmMCPercentComp { get; set; }
        public int CmTask { get; set; }
        public Nullable<int> CurrentPercentComp { get; set; }
        public Nullable<int> NewPercentComp { get; set; }
    }
}
