//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class CmMCConfPhoneResult
    {
        public System.Guid CmMCConfPhoneResultsID { get; set; }
        public int CmMCConfPhoneResultsIndex { get; set; }
        public int CmMCConfPhone { get; set; }
        public string CurrentConfPhone { get; set; }
        public string NewConfPhone { get; set; }
    }
}
