//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class CmMCETRuleset
    {
        public System.Guid CmMCETRulesetID { get; set; }
        public int CmMCETRulesetIndex { get; set; }
        public System.Guid CurrentETRuleset { get; set; }
        public System.Guid NewETRuleset { get; set; }
        public Nullable<System.Guid> CurrentEventCode { get; set; }
        public Nullable<System.Guid> NewEventCode { get; set; }
    }
}
