//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionGroupDetail
    {
        public System.Guid CollectionGroupDetailID { get; set; }
        public string CollectionGroup { get; set; }
        public decimal FromAmount { get; set; }
        public Nullable<decimal> ToAmount { get; set; }
        public string CollectionCurrency { get; set; }
        public Nullable<System.DateTime> InvoiceDueDate { get; set; }
        public string Workflow { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
