//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCard
    {
        public System.Guid CostCardID { get; set; }
        public int CostIndex { get; set; }
        public Nullable<int> OrigCostCard { get; set; }
        public string Office { get; set; }
        public string Source { get; set; }
        public System.DateTime WorkDate { get; set; }
        public System.DateTime PostDate { get; set; }
        public string Currency { get; set; }
        public System.DateTime CurrDate { get; set; }
        public int Matter { get; set; }
        public int BillMatter { get; set; }
        public int Timekeeper { get; set; }
        public System.Guid WorkMattEffDate { get; set; }
        public System.Guid BillMattEffDate { get; set; }
        public System.Guid TkprEffDate { get; set; }
        public byte IsActive { get; set; }
        public byte IsNB { get; set; }
        public Nullable<decimal> ResPct { get; set; }
        public byte IsNoCharge { get; set; }
        public Nullable<decimal> OrigAmt { get; set; }
        public Nullable<int> ChrgCard { get; set; }
        public Nullable<decimal> ChargeAmt { get; set; }
        public string EntryUnitType { get; set; }
        public Nullable<int> EntryUnit { get; set; }
        public decimal WorkQty { get; set; }
        public decimal WorkRate { get; set; }
        public decimal WorkAmt { get; set; }
        public Nullable<decimal> StdRate { get; set; }
        public string StdCurrency { get; set; }
        public Nullable<decimal> StdAmt { get; set; }
        public int Language { get; set; }
        public string Narrative { get; set; }
        public string Narrative_UnformattedText { get; set; }
        public string InternalComments { get; set; }
        public string CostType { get; set; }
        public string TransactionType { get; set; }
        public byte IsHardCost { get; set; }
        public string TaxJurisdiction { get; set; }
        public Nullable<System.Guid> Phase { get; set; }
        public Nullable<System.Guid> Task { get; set; }
        public Nullable<System.Guid> Activity { get; set; }
        public string TaxCode { get; set; }
        public string EditTranType { get; set; }
        public string Disposition { get; set; }
        public string ReasonType { get; set; }
        public Nullable<int> ProfMaster { get; set; }
        public Nullable<int> InvMaster { get; set; }
        public Nullable<int> Voucher { get; set; }
        public Nullable<decimal> OrigQty { get; set; }
        public string OrigCurrency { get; set; }
        public Nullable<decimal> OrigRate { get; set; }
        public string InputTaxCode { get; set; }
        public string WorkType { get; set; }
        public string PurgeType { get; set; }
        public Nullable<System.DateTime> WIPRemoveDate { get; set; }
        public Nullable<decimal> UnitCurrRate { get; set; }
        public Nullable<decimal> FirmCurrRate { get; set; }
        public Nullable<decimal> UnitCurrRateStd { get; set; }
        public Nullable<decimal> FirmCurrRateStd { get; set; }
        public Nullable<decimal> WIPQty { get; set; }
        public Nullable<decimal> WIPRate { get; set; }
        public Nullable<decimal> WIPAmt { get; set; }
        public byte IsDisplay { get; set; }
        public string LoadNumber { get; set; }
        public string LoadSource { get; set; }
        public string LoadGroup { get; set; }
        public string RateCalcList { get; set; }
        public string RefCurrency { get; set; }
        public Nullable<decimal> RefRate { get; set; }
        public Nullable<decimal> RefAmt { get; set; }
        public byte IsSummarize { get; set; }
        public System.DateTime GLDate { get; set; }
        public Nullable<int> AuthTimekeeper { get; set; }
        public Nullable<int> SpvTimekeeper { get; set; }
        public Nullable<int> ParCostIndex { get; set; }
        public string MatrixTaxCode { get; set; }
        public Nullable<decimal> Rpt1CurrRate { get; set; }
        public Nullable<decimal> Rpt2CurrRate { get; set; }
        public Nullable<decimal> Rpt3CurrRate { get; set; }
        public Nullable<decimal> Rpt1CurrRateStd { get; set; }
        public Nullable<decimal> Rpt2CurrRateStd { get; set; }
        public Nullable<decimal> Rpt3CurrRateStd { get; set; }
        public Nullable<int> PrevProfMaster { get; set; }
        public string ConversionRefNum { get; set; }
        public string WHTaxCode { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string LastPurgeType { get; set; }
        public string WHTaxReason { get; set; }
        public Nullable<System.Guid> Phase2 { get; set; }
        public Nullable<System.Guid> Task2 { get; set; }
        public Nullable<System.Guid> Activity2 { get; set; }
        public Nullable<int> ProfDetailEdit { get; set; }
        public string ConvSource { get; set; }
        public string ConvGroup { get; set; }
    
        public virtual Activity Activity1 { get; set; }
        public virtual Activity Activity3 { get; set; }
        public virtual MattDate MattDate { get; set; }
        public virtual MattDate MattDate1 { get; set; }
        public virtual Phase Phase1 { get; set; }
        public virtual Phase Phase3 { get; set; }
        public virtual Task Task1 { get; set; }
        public virtual Task Task3 { get; set; }
        public virtual TkprDate TkprDate { get; set; }
    }
}
