//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCardSum
    {
        public System.Guid CostCardSumID { get; set; }
        public int CostCard { get; set; }
        public System.DateTime CurrDate { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> WorkAmtBill { get; set; }
        public Nullable<decimal> BillAmtBill { get; set; }
        public Nullable<decimal> WorkAmtColl { get; set; }
        public Nullable<decimal> BillAmtWDn { get; set; }
        public Nullable<decimal> BillAmtWUp { get; set; }
        public Nullable<decimal> BillAmtColl { get; set; }
        public Nullable<decimal> WorkAmtWOff { get; set; }
        public Nullable<decimal> BillAmtWOff { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
