//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public System.Guid CountryID { get; set; }
        public string Code { get; set; }
        public string UNCode { get; set; }
        public string Description { get; set; }
        public byte IsDefault { get; set; }
        public byte IsEC { get; set; }
        public Nullable<System.Guid> LangDescription { get; set; }
        public byte IsStock { get; set; }
    }
}
