//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyDateList
    {
        public System.Guid CurrencyDateListID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string TimeDateMethod { get; set; }
        public string TimeCurrencyType { get; set; }
        public string TimeRoundingMethod { get; set; }
        public string CostDateMethod { get; set; }
        public string CostCurrencyType { get; set; }
        public string CostRoundingMethod { get; set; }
        public string ChrgDateMethod { get; set; }
        public string ChrgCurrencyType { get; set; }
        public string ChrgRoundingMethod { get; set; }
        public byte IsActive { get; set; }
        public byte Is_Default { get; set; }
        public string SortString { get; set; }
        public byte IsStock { get; set; }
    }
}
