//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataValidationRun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataValidationRun()
        {
            this.DataValidationRunDetails = new HashSet<DataValidationRunDetail>();
            this.DataValidationRunEvents = new HashSet<DataValidationRunEvent>();
        }
    
        public System.Guid DataValidationRunID { get; set; }
        public string RunName { get; set; }
        public Nullable<System.DateTime> RunTime { get; set; }
        public string Comments { get; set; }
        public byte IsErrorsOnly { get; set; }
        public Nullable<byte> IsBackground { get; set; }
        public Nullable<int> TopErrorRows { get; set; }
        public Nullable<System.Guid> RunUser { get; set; }
        public string EmailTo { get; set; }
        public string ClientCode { get; set; }
        public Nullable<byte> SendEmail { get; set; }
        public string EmailFrom { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual NxFWKUser NxFWKUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataValidationRunDetail> DataValidationRunDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataValidationRunEvent> DataValidationRunEvents { get; set; }
    }
}
