//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeptOffCollGroupLink
    {
        public System.Guid DeptOffCollGroupLinkID { get; set; }
        public System.Guid CollGrpSrchSeq { get; set; }
        public string Department { get; set; }
        public string Office { get; set; }
        public string CollectionGroup { get; set; }
        public string CollectionItemLevelType { get; set; }
        public byte IsInvoiceAccumulated { get; set; }
    
        public virtual CollectionGroupSearchSequence CollectionGroupSearchSequence { get; set; }
    }
}
