//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class DupSearchColEntityJoin
    {
        public System.Guid DupSearchColEntityJoinsID { get; set; }
        public string MainArchetypeName { get; set; }
        public string MainArchetypeForeignKey { get; set; }
        public string JoinArchetypeName { get; set; }
        public string JoinArchetypePrimaryKey { get; set; }
        public System.Guid DupSearchCol { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual DupSearchCol DupSearchCol1 { get; set; }
    }
}
