//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBillValListRule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EBillValListRule()
        {
            this.CardEBillValRuns = new HashSet<CardEBillValRun>();
            this.EBillValListRulesDetails = new HashSet<EBillValListRulesDetail>();
        }
    
        public System.Guid EBillValListRulesID { get; set; }
        public string EBillValList { get; set; }
        public string EBillRule { get; set; }
        public byte IsActive { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Value1 { get; set; }
        public string Value2 { get; set; }
        public string Value3 { get; set; }
        public string Value4 { get; set; }
        public string Value5 { get; set; }
        public byte IsPendingWarning { get; set; }
        public byte IsPendingError { get; set; }
        public byte IsPostWarning { get; set; }
        public byte IsPostError { get; set; }
        public byte IsProformaGen { get; set; }
        public byte IsProformaEdit { get; set; }
        public byte IsBillWarning { get; set; }
        public byte IsBillError { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardEBillValRun> CardEBillValRuns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBillValListRulesDetail> EBillValListRulesDetails { get; set; }
    }
}
