//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBillRule
    {
        public System.Guid EBillRuleID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public byte IsStock { get; set; }
        public string EBillRuleCategory { get; set; }
        public string EBillRuleType { get; set; }
        public string SQLCard { get; set; }
        public string SQLProf { get; set; }
        public string SQLPend { get; set; }
        public string FunctionName { get; set; }
        public byte IsTimekeeper { get; set; }
        public byte IsTitle { get; set; }
        public byte IsRate { get; set; }
        public byte IsCostType { get; set; }
        public byte IsTimeType { get; set; }
        public byte IsAdjustType { get; set; }
        public byte IsPhase { get; set; }
        public byte IsTask { get; set; }
        public byte IsActivity { get; set; }
        public string WarningMessage { get; set; }
        public string ErrorMessage { get; set; }
        public string Value1Label { get; set; }
        public string Value2Label { get; set; }
        public string Value3Label { get; set; }
        public string Value4Label { get; set; }
        public string Value5Label { get; set; }
        public string SortString { get; set; }
        public byte IsString { get; set; }
        public byte IsInteger { get; set; }
        public byte IsDate { get; set; }
        public byte IsDecimal { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public byte IsPayee { get; set; }
        public byte IsPhase2 { get; set; }
        public byte IsTask2 { get; set; }
        public byte IsActivity2 { get; set; }
    }
}
