//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityMergeDetailOrg
    {
        public System.Guid EntityMergeDetailOrgID { get; set; }
        public int EntityOrg { get; set; }
        public byte ChkDunBNumber { get; set; }
        public byte ChkUltimateDunB { get; set; }
        public byte ChkStockSymbol { get; set; }
        public byte ChkStateOfInc { get; set; }
        public byte ChkOrganizationType { get; set; }
        public byte ChkOrgName { get; set; }
    }
}
