//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpDetailAirline
    {
        public System.Guid ExpDetailAirlineID { get; set; }
        public string CarrierCode { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string ArrivalCity { get; set; }
        public string DepartureCity { get; set; }
    }
}
