//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpStatu
    {
        public System.Guid ExpStatusID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public byte IsSubmitted { get; set; }
        public byte IsDenied { get; set; }
        public byte IsHoldRcpt { get; set; }
        public byte IsApproved { get; set; }
        public byte IsVoucher { get; set; }
        public byte IsPaid { get; set; }
        public byte IsNew { get; set; }
    }
}
