//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class FABook
    {
        public System.Guid FABookID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string BookType { get; set; }
        public int FiscalYearStartMonth { get; set; }
        public byte IsCatchupDepr { get; set; }
        public string FABookGroup { get; set; }
        public byte IsSalvageUsed { get; set; }
        public byte IsCalendarRpt { get; set; }
    }
}
