//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAPostingMask
    {
        public System.Guid FAPostingMasksID { get; set; }
        public string GLType { get; set; }
        public string FABook { get; set; }
        public Nullable<System.Guid> GLUnit { get; set; }
        public int AssetCost { get; set; }
        public int AccumDepr { get; set; }
        public int AssetClearing { get; set; }
        public int DeprExpense { get; set; }
        public int Section179Exp { get; set; }
        public Nullable<int> Section179Recap { get; set; }
        public int RetireProceeds { get; set; }
        public int DisposalCost { get; set; }
        public int RetireGainLoss { get; set; }
        public byte IsDefault { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual GLUnit GLUnit1 { get; set; }
    }
}
