//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowUpCollectionAction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FollowUpCollectionAction()
        {
            this.ScheduledCollectionActions = new HashSet<ScheduledCollectionAction>();
        }
    
        public System.Guid FollowUpCollectionActionID { get; set; }
        public System.Guid CollectionCall { get; set; }
        public string FollowUpAction { get; set; }
        public System.Guid FollowUpActionBy { get; set; }
        public Nullable<int> ActionPriority { get; set; }
        public System.DateTime FollowUpActionDate { get; set; }
        public Nullable<System.DateTime> FollowUpActionCompletionDate { get; set; }
        public Nullable<System.Guid> CollPromiseScheduleDetail { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual CollectionCallHistory CollectionCallHistory { get; set; }
        public virtual CollPromiseScheduleDetail CollPromiseScheduleDetail1 { get; set; }
        public virtual NxUser NxUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduledCollectionAction> ScheduledCollectionActions { get; set; }
    }
}
