//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class FtxCollection
    {
        public System.Guid FtxCollectionID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> MostRecentDocDeletion { get; set; }
        public Nullable<System.DateTime> LastAttemptedReclaimMerge { get; set; }
        public Nullable<int> ReclaimMergeStatus { get; set; }
        public string MetaData { get; set; }
    }
}
