//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTXOpenTextColl
    {
        public System.Guid FTXOpenTextCollID { get; set; }
        public int OpenTextCollIndex { get; set; }
        public string CollectionName { get; set; }
        public System.Guid FTXOpenTextCol { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public Nullable<int> DocIndex { get; set; }
        public Nullable<int> DocVersion { get; set; }
        public string Description { get; set; }
        public byte IsNeedReIndex { get; set; }
        public Nullable<System.Guid> NxNtfTask { get; set; }
    
        public virtual FTXOpenText FTXOpenText { get; set; }
        public virtual NxNtfTask NxNtfTask1 { get; set; }
    }
}
