//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTXSGenColField
    {
        public System.Guid FTXSGenColFieldsID { get; set; }
        public string AttrColumn { get; set; }
        public byte IsPhonetic { get; set; }
        public string WhereCondition { get; set; }
        public string ModifyDateColumn { get; set; }
        public string UniqueColumn { get; set; }
        public string FTXSGenericDBColl { get; set; }
        public string ArchCode { get; set; }
        public string ProviderCode { get; set; }
        public Nullable<int> AttrDataType { get; set; }
        public string SchemaName { get; set; }
    }
}
