//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTXS3EDBColl
    {
        public System.Guid FTXS3EDBCollID { get; set; }
        public int DBColIndex { get; set; }
        public string CollectionName { get; set; }
        public System.Guid FTXS3EDB { get; set; }
        public string Description { get; set; }
    
        public virtual FTXS3EDB FTXS3EDB1 { get; set; }
    }
}
