//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLAllocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GLAllocation()
        {
            this.GLAllocJournals = new HashSet<GLAllocJournal>();
        }
    
        public System.Guid GLAllocationID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string AllocSrcCol { get; set; }
        public string RestrictCurrency { get; set; }
        public string CurrencyType { get; set; }
        public string CalcCurrency { get; set; }
        public byte IsSrcConstant { get; set; }
        public Nullable<decimal> SrcConstant { get; set; }
        public Nullable<int> SrcGLAcct { get; set; }
        public string SourcePeriod { get; set; }
        public string SrcBook { get; set; }
        public string SrcAct01 { get; set; }
        public string SrcAct02 { get; set; }
        public string SrcAct03 { get; set; }
        public string SrcAct04 { get; set; }
        public string SrcAct05 { get; set; }
        public string SrcAct06 { get; set; }
        public string SrcAct07 { get; set; }
        public string SrcAct08 { get; set; }
        public string SrcAct09 { get; set; }
        public string SrcAct10 { get; set; }
        public string SrcAct11 { get; set; }
        public string SrcAct12 { get; set; }
        public string SrcAct13 { get; set; }
        public string SrcAct14 { get; set; }
        public string SrcAct15 { get; set; }
        public string RatioPeriod { get; set; }
        public string RatioBook { get; set; }
        public Nullable<int> NumGLAcct { get; set; }
        public string NumAct01 { get; set; }
        public string NumAct02 { get; set; }
        public string NumAct03 { get; set; }
        public string NumAct04 { get; set; }
        public string NumAct05 { get; set; }
        public string NumAct06 { get; set; }
        public string NumAct07 { get; set; }
        public string NumAct08 { get; set; }
        public string NumAct09 { get; set; }
        public string NumAct10 { get; set; }
        public string NumAct11 { get; set; }
        public string NumAct12 { get; set; }
        public string NumAct13 { get; set; }
        public string NumAct14 { get; set; }
        public string NumAct15 { get; set; }
        public Nullable<int> BaseGLAcct { get; set; }
        public string BaseAct01 { get; set; }
        public string BaseAct02 { get; set; }
        public string BaseAct03 { get; set; }
        public string BaseAct04 { get; set; }
        public string BaseAct05 { get; set; }
        public string BaseAct06 { get; set; }
        public string BaseAct07 { get; set; }
        public string BaseAct08 { get; set; }
        public string BaseAct09 { get; set; }
        public string BaseAct10 { get; set; }
        public string BaseAct11 { get; set; }
        public string BaseAct12 { get; set; }
        public string BaseAct13 { get; set; }
        public string BaseAct14 { get; set; }
        public string BaseAct15 { get; set; }
        public Nullable<int> TargetGLMask { get; set; }
        public Nullable<int> TargetGLAcct { get; set; }
        public string TargetGLType { get; set; }
        public Nullable<int> OffsetGLMask { get; set; }
        public Nullable<int> OffsetGLAcct { get; set; }
        public string OffsetAct01 { get; set; }
        public string OffsetAct02 { get; set; }
        public string OffsetAct03 { get; set; }
        public string OffsetAct04 { get; set; }
        public string OffsetAct05 { get; set; }
        public string OffsetAct06 { get; set; }
        public string OffsetAct07 { get; set; }
        public string OffsetAct08 { get; set; }
        public string OffsetAct09 { get; set; }
        public string OffsetAct10 { get; set; }
        public string OffsetAct11 { get; set; }
        public string OffsetAct12 { get; set; }
        public string OffsetAct13 { get; set; }
        public string OffsetAct14 { get; set; }
        public string OffsetAct15 { get; set; }
        public byte ClearUnitFirm { get; set; }
        public Nullable<System.DateTime> CurrencyDate { get; set; }
        public string RequestedUnits { get; set; }
        public string RequestedGlAccts { get; set; }
        public Nullable<System.Guid> TestPeriod { get; set; }
        public string Unit { get; set; }
        public string UnitGroup { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual UnitPeriod UnitPeriod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GLAllocJournal> GLAllocJournals { get; set; }
    }
}
