//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLClearLine
    {
        public System.Guid GLClearLineID { get; set; }
        public int GLClearHdr { get; set; }
        public int GLDetail { get; set; }
        public Nullable<System.DateTime> GLDate { get; set; }
        public string Description { get; set; }
        public string ClearComment { get; set; }
        public Nullable<int> GLClearReg { get; set; }
        public string Currency { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
