//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLTypeAccess
    {
        public System.Guid GLTypeAccessID { get; set; }
        public string GLType { get; set; }
        public Nullable<System.Guid> UserName { get; set; }
        public Nullable<System.Guid> Role { get; set; }
        public System.DateTime EnableDate { get; set; }
        public Nullable<System.DateTime> DisableDate { get; set; }
        public byte IsAccessByUser { get; set; }
        public Nullable<int> FuturePeriods { get; set; }
    
        public virtual NxRole NxRole { get; set; }
        public virtual NxUser NxUser { get; set; }
    }
}
