//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICBClearingSetup
    {
        public System.Guid ICBClearingSetupID { get; set; }
        public string Description { get; set; }
        public string GLBook { get; set; }
        public string GLType { get; set; }
        public string ProfStatus { get; set; }
        public string Comment { get; set; }
        public string Currency { get; set; }
        public byte IsIgnoreICBCurrency { get; set; }
        public string SortString { get; set; }
        public byte IsNonBillable { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
