//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceCollectionItem
    {
        public System.Guid InvoiceCollectionItemID { get; set; }
        public System.Guid InvPayor { get; set; }
    
        public virtual InvPayor InvPayor1 { get; set; }
    }
}
