//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvReverseEventDetail
    {
        public System.Guid InvReverseEventDetailID { get; set; }
        public int InvReverseEvent { get; set; }
        public int InvMaster { get; set; }
        public byte IsReversePayment { get; set; }
        public byte IsReinstateTrustBal { get; set; }
        public string UnalType { get; set; }
        public string NewCrNoteNumber { get; set; }
        public Nullable<byte> IsConversionInv { get; set; }
        public Nullable<byte> IsCreateProfRecords { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
