//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class JM
    {
        public System.Guid JMID { get; set; }
        public int PostIndex { get; set; }
        public string JMStatusList { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string PostSourceList { get; set; }
        public string Description { get; set; }
        public string AggMethodList { get; set; }
        public Nullable<byte> INTranSumm { get; set; }
        public Nullable<byte> INUnitSumm { get; set; }
        public Nullable<byte> INFirmSumm { get; set; }
        public Nullable<System.Guid> PostingGroupID { get; set; }
        public Nullable<System.DateTime> PostingTimestamp { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string GLType { get; set; }
        public string ConvNumber { get; set; }
        public string ConvSource { get; set; }
        public string ConvGroup { get; set; }
    }
}
