//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class MattInterestGenBack
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MattInterestGenBack()
        {
            this.MattInterestGenDetailBacks = new HashSet<MattInterestGenDetailBack>();
        }
    
        public System.Guid MattInterestGenBackID { get; set; }
        public System.DateTime InterestDate { get; set; }
        public string MatterPredicate { get; set; }
        public string ARDetailPredicate { get; set; }
        public string Comment { get; set; }
        public string ProfStatus { get; set; }
        public Nullable<System.DateTime> LastInterestDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MattInterestGenDetailBack> MattInterestGenDetailBacks { get; set; }
    }
}
