//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class MattDate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MattDate()
        {
            this.BalHistARs = new HashSet<BalHistAR>();
            this.BalHistWIPs = new HashSet<BalHistWIP>();
            this.BillSums = new HashSet<BillSum>();
            this.BillSums1 = new HashSet<BillSum>();
            this.BillSums2 = new HashSet<BillSum>();
            this.BillSums3 = new HashSet<BillSum>();
            this.BillSums4 = new HashSet<BillSum>();
            this.BillSums5 = new HashSet<BillSum>();
            this.ChrgBills = new HashSet<ChrgBill>();
            this.ChrgBills1 = new HashSet<ChrgBill>();
            this.ChrgCards = new HashSet<ChrgCard>();
            this.ChrgCards1 = new HashSet<ChrgCard>();
            this.ChrgCardPendings = new HashSet<ChrgCardPending>();
            this.ChrgRcpts = new HashSet<ChrgRcpt>();
            this.ChrgRcpts1 = new HashSet<ChrgRcpt>();
            this.CostBills = new HashSet<CostBill>();
            this.CostBills1 = new HashSet<CostBill>();
            this.CostCards = new HashSet<CostCard>();
            this.CostCards1 = new HashSet<CostCard>();
            this.CostCardPendings = new HashSet<CostCardPending>();
            this.CostRcpts = new HashSet<CostRcpt>();
            this.CostRcpts1 = new HashSet<CostRcpt>();
            this.FirmBillSums = new HashSet<FirmBillSum>();
            this.FirmBillSums1 = new HashSet<FirmBillSum>();
            this.FirmBillSums2 = new HashSet<FirmBillSum>();
            this.FirmBillSums3 = new HashSet<FirmBillSum>();
            this.FirmBillSums4 = new HashSet<FirmBillSum>();
            this.FirmBillSums5 = new HashSet<FirmBillSum>();
            this.MattOrgTkprs = new HashSet<MattOrgTkpr>();
            this.MattPrlfTkprs = new HashSet<MattPrlfTkpr>();
            this.ProfDetails = new HashSet<ProfDetail>();
            this.ProfDetails1 = new HashSet<ProfDetail>();
            this.ProfDetails2 = new HashSet<ProfDetail>();
            this.TimeBills = new HashSet<TimeBill>();
            this.TimeBills1 = new HashSet<TimeBill>();
            this.Timecards = new HashSet<Timecard>();
            this.Timecards1 = new HashSet<Timecard>();
            this.TimeCardPendings = new HashSet<TimeCardPending>();
            this.TimeRcpts = new HashSet<TimeRcpt>();
            this.TimeRcpts1 = new HashSet<TimeRcpt>();
            this.WPAmounts = new HashSet<WPAmount>();
            this.WPAmounts1 = new HashSet<WPAmount>();
        }
    
        public System.Guid MattDateID { get; set; }
        public Nullable<int> MatterLkUp { get; set; }
        public System.DateTime EffStart { get; set; }
        public string Office { get; set; }
        public string PracticeGroup { get; set; }
        public string Department { get; set; }
        public string Section { get; set; }
        public string Arrangement { get; set; }
        public string TkprTeam { get; set; }
        public string ReservesGroup { get; set; }
        public string MattSplitType { get; set; }
        public int BillTkpr { get; set; }
        public int RspTkpr { get; set; }
        public int SpvTkpr { get; set; }
        public string PTAGroup { get; set; }
        public string PTAGroupCost { get; set; }
        public string PTAGroupChrg { get; set; }
        public Nullable<System.DateTime> NxEndDate { get; set; }
        public Nullable<System.DateTime> NxStartDate { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string PTAGroup2 { get; set; }
        public string PTAGroupCost2 { get; set; }
        public string PTAGroupChrg2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BalHistAR> BalHistARs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BalHistWIP> BalHistWIPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillSum> BillSums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillSum> BillSums1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillSum> BillSums2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillSum> BillSums3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillSum> BillSums4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillSum> BillSums5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChrgBill> ChrgBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChrgBill> ChrgBills1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChrgCard> ChrgCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChrgCard> ChrgCards1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChrgCardPending> ChrgCardPendings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChrgRcpt> ChrgRcpts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChrgRcpt> ChrgRcpts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostBill> CostBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostBill> CostBills1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostCard> CostCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostCard> CostCards1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostCardPending> CostCardPendings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostRcpt> CostRcpts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostRcpt> CostRcpts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmBillSum> FirmBillSums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmBillSum> FirmBillSums1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmBillSum> FirmBillSums2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmBillSum> FirmBillSums3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmBillSum> FirmBillSums4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmBillSum> FirmBillSums5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MattOrgTkpr> MattOrgTkprs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MattPrlfTkpr> MattPrlfTkprs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfDetail> ProfDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfDetail> ProfDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfDetail> ProfDetails2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeBill> TimeBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeBill> TimeBills1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timecard> Timecards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timecard> Timecards1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeCardPending> TimeCardPendings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeRcpt> TimeRcpts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeRcpt> TimeRcpts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WPAmount> WPAmounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WPAmount> WPAmounts1 { get; set; }
    }
}
