//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetricEvent
    {
        public System.Guid MetricEventID { get; set; }
        public Nullable<System.Guid> MetricObject { get; set; }
        public string MxObjectCode { get; set; }
    
        public virtual NxMetric NxMetric { get; set; }
    }
}
