//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class MxApCashRequirement
    {
        public System.Guid MxApCashRequirementsID { get; set; }
        public string CurrencyDate { get; set; }
        public string ReqVendors { get; set; }
        public Nullable<System.DateTime> CurrencyAsOfDate { get; set; }
        public string PayeePred { get; set; }
    }
}
