//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class MxAVRProfitabilityRun
    {
        public System.Guid MxAVRProfitabilityRunID { get; set; }
        public string PrftCostRateType { get; set; }
        public Nullable<byte> UseWorkDateForCurrConv { get; set; }
        public Nullable<byte> UseExpenseDateForCurrConv { get; set; }
        public string Column1 { get; set; }
        public string Column2 { get; set; }
        public string Column3 { get; set; }
        public string Column4 { get; set; }
        public string Column5 { get; set; }
        public string Column6 { get; set; }
        public string Categories1 { get; set; }
        public string Categories2 { get; set; }
        public string Categories3 { get; set; }
        public string Categories4 { get; set; }
        public string Categories5 { get; set; }
        public string Categories6 { get; set; }
    }
}
