//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class MxAVRInventoryRun
    {
        public System.Guid MxAVRInventoryRunID { get; set; }
        public Nullable<System.Guid> WIPAgingCode { get; set; }
        public string WIPReportValues { get; set; }
        public Nullable<byte> IsIncludeNB { get; set; }
        public Nullable<System.Guid> ARAgingCode { get; set; }
        public Nullable<byte> IsAgeByDueDate { get; set; }
        public Nullable<byte> IsIncWorkTkprAR { get; set; }
        public Nullable<decimal> RoundTolerance { get; set; }
        public string WIPAge1 { get; set; }
        public string WIPAge2 { get; set; }
        public string WIPAge3 { get; set; }
        public string WIPAge4 { get; set; }
        public string WIPAge5 { get; set; }
        public string ARAge1 { get; set; }
        public string ARAge2 { get; set; }
        public string ARAge3 { get; set; }
        public string ARAge4 { get; set; }
        public string ARAge5 { get; set; }
    
        public virtual AgingScheme AgingScheme { get; set; }
        public virtual AgingScheme AgingScheme1 { get; set; }
    }
}
