//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class MxCashRequirement
    {
        public System.Guid MxCashRequirementID { get; set; }
        public System.DateTime SDate { get; set; }
        public System.Guid AgingCode { get; set; }
        public string ReqPayee { get; set; }
        public string ReqVoucher { get; set; }
        public byte Discount { get; set; }
        public Nullable<System.DateTime> AsofDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string BasedOn { get; set; }
    
        public virtual AgingScheme AgingScheme { get; set; }
    }
}
