//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class MxChrgGlReconcilationRun
    {
        public System.Guid MxChrgGlReconcilationRunID { get; set; }
        public Nullable<byte> IsIncludeWorkPostings { get; set; }
        public Nullable<byte> IsIncludeBillPostings { get; set; }
        public Nullable<byte> IsIncludeRcptPostings { get; set; }
        public Nullable<byte> IsIncludeNoPostings { get; set; }
        public string GLType { get; set; }
        public string ChrgCard { get; set; }
        public string ChrgBill { get; set; }
        public string ChrgRcpt { get; set; }
        public Nullable<byte> IsIncludeDirectGLPostings { get; set; }
        public Nullable<byte> IsBillableOnly { get; set; }
    }
}
