//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class MxCJBalancingParam
    {
        public System.Guid MxCJBalancingParamID { get; set; }
        public Nullable<int> BankGroup { get; set; }
        public Nullable<int> BankAcct { get; set; }
        public string TranNum { get; set; }
        public string ReconStatus { get; set; }
        public string APPaymentPred { get; set; }
        public string ReceiptPred { get; set; }
        public string GJPred { get; set; }
        public string NewCashTranPred { get; set; }
        public string TrustCheckPred { get; set; }
        public string TrustReceiptPred { get; set; }
        public string TrustAdjPred { get; set; }
        public string TrustTransferPred { get; set; }
        public Nullable<System.DateTime> GLStartDate { get; set; }
        public Nullable<System.DateTime> GLEndDate { get; set; }
        public string GLBook { get; set; }
        public Nullable<int> BankStmt { get; set; }
        public Nullable<System.Guid> Worksheet { get; set; }
    
        public virtual BankRecWorkHdr BankRecWorkHdr { get; set; }
    }
}
