//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class MxClientFeesPaidRankingRun
    {
        public System.Guid MxClientFeesPaidRankingRunID { get; set; }
        public byte IsIncludeGroups { get; set; }
        public Nullable<int> CutoffAmount { get; set; }
        public Nullable<int> TopNumber { get; set; }
        public string ReqClients { get; set; }
        public byte IsIncludeReversals { get; set; }
        public byte IsIncludeCollections { get; set; }
        public byte IsIncludeWriteoffs { get; set; }
    }
}
