//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class MxCostCardLife
    {
        public System.Guid MxCostCardLifeID { get; set; }
        public Nullable<int> Costcard { get; set; }
        public string CostCardFilter { get; set; }
        public Nullable<int> Timekeeper { get; set; }
        public Nullable<int> Matter { get; set; }
        public string VoucherFilter { get; set; }
    }
}
