//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class MxCollectionInvoiceParam
    {
        public System.Guid MxCollectionInvoiceParamID { get; set; }
        public string Clients { get; set; }
        public string Payors { get; set; }
        public string Matters { get; set; }
        public string BillTkprs { get; set; }
        public string SupvTkprs { get; set; }
        public string Collectors { get; set; }
        public byte IsOpen { get; set; }
        public byte IsAboveThreshold { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public byte IsClosed { get; set; }
        public Nullable<System.DateTime> CurrencyAsOfDate { get; set; }
    }
}
