//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class MxFADeprExpenseRpt
    {
        public System.Guid MxFADeprExpenseRptID { get; set; }
        public string FABook { get; set; }
        public int FiscalYear { get; set; }
        public Nullable<System.DateTime> AsOfDate { get; set; }
        public string FAAsset { get; set; }
        public Nullable<int> FiscalYearStartMonth { get; set; }
        public byte IsPoststoGL { get; set; }
    }
}
