//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class MxGLDetailRun
    {
        public System.Guid MxGLDetailRunID { get; set; }
        public string GLBook { get; set; }
        public Nullable<int> GLAcct { get; set; }
        public string CurrCode { get; set; }
        public string CurrencyType { get; set; }
        public string CurrencyCalcDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<byte> IsNoCurrencyConversion { get; set; }
        public Nullable<byte> IsUseReportingCurrencies { get; set; }
        public Nullable<System.DateTime> CurrencyAsOfDate { get; set; }
        public string GLNaturalHigh { get; set; }
        public string GLNaturalLow { get; set; }
        public string GLUnitHigh { get; set; }
        public string GLUnitLow { get; set; }
        public string GLTimekeeperHigh { get; set; }
        public string GLTimekeeperLow { get; set; }
        public string GLDepartmentHigh { get; set; }
        public string GLDepartmentLow { get; set; }
        public string GLArrangementHigh { get; set; }
        public string GLArrangementLow { get; set; }
        public string GLPracticeGroupHigh { get; set; }
        public string GLPracticeGroupLow { get; set; }
        public string GLSectionHigh { get; set; }
        public string GLSectionLow { get; set; }
        public string GLOfficeHigh { get; set; }
        public string GLOfficeLow { get; set; }
        public string GLTitleHigh { get; set; }
        public string GLTitleLow { get; set; }
        public string GLWorkTypeHigh { get; set; }
        public string GLWorkTypeLow { get; set; }
        public string GLUnitLocalHigh { get; set; }
        public string GLUnitLocalLow { get; set; }
        public string GLTypeFilter { get; set; }
        public string GLBookDesc { get; set; }
        public Nullable<System.DateTime> PostedAsOfDate { get; set; }
        public byte IsIncludeOpening { get; set; }
        public byte IsIncludeCJE { get; set; }
        public Nullable<byte> IsOpenTran { get; set; }
        public byte IsIncludeOpeningByGLBook { get; set; }
        public byte IsIncludeTCJE { get; set; }
        public string GLActivityLow { get; set; }
        public string GLActivityHigh { get; set; }
    }
}
