//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class MxICBClearingRun
    {
        public System.Guid MxICBClearingRunID { get; set; }
        public string ReqClearing { get; set; }
        public Nullable<byte> IsIncludePosted { get; set; }
        public byte IsICBBillingCurrency { get; set; }
    }
}
