//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class MxMetricRun
    {
        public System.Guid MxMetricRunID { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyType { get; set; }
        public string CurrencyCalcDate { get; set; }
        public Nullable<byte> IsCurrentValues { get; set; }
        public string ReportOnDate { get; set; }
        public string ReportingPeriod { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<byte> IsUseReportingCurrencies { get; set; }
        public Nullable<byte> IsNoCurrencyConversion { get; set; }
        public Nullable<System.DateTime> CurrencyAsOfDate { get; set; }
        public string EffDateLookup { get; set; }
    }
}
