//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class MxMultiCurrencyRealization
    {
        public System.Guid MxMultiCurrencyRealizationID { get; set; }
        public byte IsUseFirmRate { get; set; }
        public string ReqMatters { get; set; }
        public byte IsIncludeZeroes { get; set; }
        public string PaymentsPeriod { get; set; }
        public Nullable<System.DateTime> PaymentsStartDate { get; set; }
        public System.DateTime PaymentsEndDate { get; set; }
        public string MetricTkprSplitList { get; set; }
    }
}
