//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class MxTrustBalance
    {
        public System.Guid MxTrustBalancesID { get; set; }
        public byte IsIncludeInactive { get; set; }
        public string ReqMatters { get; set; }
        public byte IsUseFirmRate { get; set; }
        public string ReqBalances { get; set; }
        public Nullable<int> TrustAccount { get; set; }
        public string TrustMoneyType { get; set; }
        public string TrustAcctPred { get; set; }
        public Nullable<System.DateTime> CurrencyAsOfDate { get; set; }
        public byte IsBalancingIntegrityRun { get; set; }
        public string BalancingPeriod { get; set; }
        public string BalancingPeriodOption { get; set; }
    }
}
