//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class MxTrustGLReconciliationRun
    {
        public System.Guid MxTrustGLReconciliationRunID { get; set; }
        public string TrustAcct { get; set; }
        public string Matter { get; set; }
        public Nullable<byte> IsIncludeReceipts { get; set; }
        public Nullable<byte> IsIncludeDisbursements { get; set; }
        public Nullable<byte> IsIncludeAdjustments { get; set; }
        public Nullable<byte> IsIncludeTransfers { get; set; }
        public Nullable<byte> IsIncludeChecks { get; set; }
        public string TrustReceiptDetail { get; set; }
        public string TrustDisbursement { get; set; }
        public string TrustAdjustment { get; set; }
        public string TrustTransferDetail { get; set; }
        public string TrustCheckDet { get; set; }
        public Nullable<byte> IsIncludeNoPostings { get; set; }
        public Nullable<byte> IsIncludeDirectGLPostings { get; set; }
        public string GLType { get; set; }
    }
}
