//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class MxVolumeDiscountRun
    {
        public System.Guid MxVolumeDiscountRunID { get; set; }
        public string ReqGroups { get; set; }
        public Nullable<System.DateTime> AsOfDate { get; set; }
        public Nullable<byte> IsUseProjectedAmts { get; set; }
    }
}
