//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class MxWorkingTkprInvestment
    {
        public System.Guid MxWorkingTkprInvestmentID { get; set; }
        public byte IsIncludeAll { get; set; }
        public string AsOfDateOption { get; set; }
        public Nullable<System.DateTime> AsOfDate { get; set; }
        public string ReqTkprs { get; set; }
        public System.Guid AgingCode { get; set; }
        public string AgingDateOption { get; set; }
        public System.DateTime AgingDate { get; set; }
        public byte IsIncludeWIP { get; set; }
        public byte IsIncludeAR { get; set; }
        public byte IsIncludeOA { get; set; }
        public byte IsIncludeUnallocated { get; set; }
        public string Aging1 { get; set; }
        public string Aging2 { get; set; }
        public string Aging3 { get; set; }
        public string Aging4 { get; set; }
        public string Aging5 { get; set; }
        public string Aging6 { get; set; }
        public string ReqTkprDate { get; set; }
        public string ReqMatters { get; set; }
        public string ReqMattDate { get; set; }
        public byte IsUseWorkDateForAging { get; set; }
        public byte IsIncludeBillBeforeWork { get; set; }
    
        public virtual AgingScheme AgingScheme { get; set; }
    }
}
