//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class NtfEventBillingAR
    {
        public System.Guid NtfEventBillingARID { get; set; }
        public Nullable<decimal> AmountGreater { get; set; }
        public Nullable<decimal> AmountLess { get; set; }
        public Nullable<int> InvoiceAgeGreater { get; set; }
        public Nullable<int> InvoiceAgeLess { get; set; }
        public string MattStatus { get; set; }
        public string NtfIncludeDoubtfulsList { get; set; }
        public string InvMasterPred { get; set; }
    }
}
