//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class NtfEventUserInfo
    {
        public System.Guid NtfEventUserInfoID { get; set; }
        public Nullable<System.Guid> NxFWKUser { get; set; }
        public string Non3EUserEmailID { get; set; }
        public Nullable<System.Guid> NtfEventEmailInfo { get; set; }
        public string NtfEmailDeliveryType { get; set; }
        public Nullable<int> Timekeeper { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual NxFWKUser NxFWKUser1 { get; set; }
    }
}
