//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class NtfEmailNtfPrcList
    {
        public System.Guid NtfEmailNtfPrcListID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> NxFwkAppObject { get; set; }
        public string NtfApplicationList { get; set; }
        public Nullable<byte> IsStock { get; set; }
        public Nullable<System.Guid> DetailGroupArchetype { get; set; }
    }
}
