//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class NxBizTalkExtSNLoad
    {
        public System.Guid NxBizTalkExtSNLoadID { get; set; }
        public string Client { get; set; }
        public string Matter { get; set; }
        public string SearchReason { get; set; }
        public string Submitter { get; set; }
    }
}
