//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class NxBizTalkExtLogVoucherHdr
    {
        public System.Guid NxBizTalkExtLogVoucherHdrID { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string BeneficiaryName { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public string Invoice { get; set; }
        public string CostDesc { get; set; }
        public string GLAccountDesc { get; set; }
        public string Bank { get; set; }
        public string Status { get; set; }
        public string Terms { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string GLNumber { get; set; }
        public string Description { get; set; }
        public string TranType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Currency { get; set; }
        public string Client { get; set; }
        public string Matter { get; set; }
        public string GLAccountNumber { get; set; }
    }
}
