//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class NxBizTalkExtLogBankStDet
    {
        public System.Guid NxBizTalkExtLogBankStDetID { get; set; }
        public Nullable<System.DateTime> ClearDate { get; set; }
        public Nullable<decimal> ItemAmount { get; set; }
        public string ReferenceNumber { get; set; }
        public string TransactionDescription { get; set; }
    }
}
