//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class NxBizTalkExtLogClientEffDetail
    {
        public System.Guid NxBizTalkExtLogClientEffDetailID { get; set; }
        public Nullable<System.DateTime> EffStartDate { get; set; }
        public string BillingTkpr { get; set; }
        public string RespTkpr { get; set; }
        public string SupTkpr { get; set; }
        public Nullable<System.Guid> NxBzTkExtLogCliLoadID { get; set; }
        public string Office { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual NxBizTalkExtLogClientLoad NxBizTalkExtLogClientLoad { get; set; }
    }
}
