//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class NxDMSAttachmentDetail
    {
        public System.Guid NxDMSAttachmentDetailsID { get; set; }
        public System.Guid DMSArchetype { get; set; }
        public System.Guid NxDMSAttachmentMapping { get; set; }
        public Nullable<System.Guid> NxSyncMap { get; set; }
        public string OverrideFolder { get; set; }
    
        public virtual NxDMSAttachmentMapping NxDMSAttachmentMapping1 { get; set; }
        public virtual NxSyncMap NxSyncMap1 { get; set; }
    }
}
