//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class NxESBDynImportFieldList
    {
        public System.Guid NxESBDynImportFieldListID { get; set; }
        public Nullable<System.Guid> NxIntDynImport { get; set; }
        public string WrapCharacter { get; set; }
        public Nullable<System.Guid> Delimiter { get; set; }
        public Nullable<byte> IsALookupField { get; set; }
        public string AliasFieldName { get; set; }
    
        public virtual NxESBDynImportDelimiter NxESBDynImportDelimiter { get; set; }
        public virtual NxIntegrationImportDynamicFormat NxIntegrationImportDynamicFormat { get; set; }
    }
}
