//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class NxFullTextAppData
    {
        public System.Guid NxFullTextAppDataID { get; set; }
        public string ProviderCode { get; set; }
        public string ArchCode { get; set; }
        public string AttrCode { get; set; }
        public string AttrText { get; set; }
        public Nullable<int> AttrTextLanguage { get; set; }
        public string DataItemID { get; set; }
        public Nullable<System.DateTime> ModifiedTimeStamp { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.Guid> BatchID { get; set; }
        public Nullable<System.DateTime> HandledTimeStamp { get; set; }
        public Nullable<byte> IsDeleted { get; set; }
        public Nullable<System.Guid> FrameworkItemID { get; set; }
        public Nullable<System.DateTime> ErrorTimeStamp { get; set; }
        public Nullable<int> ErrorReason { get; set; }
        public Nullable<int> ErrorCount { get; set; }
        public Nullable<System.Guid> MessageID { get; set; }
        public Nullable<System.DateTime> AssignedTimeStamp { get; set; }
        public Nullable<System.Guid> ReindexBatchID { get; set; }
        public string SourceCollection { get; set; }
    }
}
