//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class NxFWKAppObjectOverride
    {
        public System.Guid NxFWKAppObjectOverrideID { get; set; }
        public Nullable<System.Guid> AppObject { get; set; }
        public Nullable<System.Guid> OverrideUser { get; set; }
        public string OverrideXML { get; set; }
        public int OverrideVersion { get; set; }
        public Nullable<System.Guid> PIID { get; set; }
    }
}
