//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class NxFWKProcessItemStep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NxFWKProcessItemStep()
        {
            this.NxFWKCollaborations = new HashSet<NxFWKCollaboration>();
            this.NxFWKCollaborationComments = new HashSet<NxFWKCollaborationComment>();
        }
    
        public System.Guid ProcItemStepID { get; set; }
        public System.Guid ProcItemID { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> LastAccessTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public System.Guid CurrentUserId { get; set; }
        public string CurrentStepID { get; set; }
        public string StepType { get; set; }
        public Nullable<System.DateTime> TimeoutDateTime { get; set; }
        public string ServerName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NxFWKCollaboration> NxFWKCollaborations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NxFWKCollaborationComment> NxFWKCollaborationComments { get; set; }
        public virtual NxFWKProcessItem NxFWKProcessItem { get; set; }
    }
}
