//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class NxIntegrationImportFileFormat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NxIntegrationImportFileFormat()
        {
            this.BizTalkImportFileEvents = new HashSet<BizTalkImportFileEvent>();
        }
    
        public System.Guid NxIntegrationImportFileFormatID { get; set; }
        public string FileName { get; set; }
        public string FileLocation { get; set; }
        public Nullable<byte> ArchiveFile { get; set; }
        public string ArchiveFileLocation { get; set; }
        public string ImportDataLocation { get; set; }
        public Nullable<byte> DeleteImportFile { get; set; }
        public Nullable<System.Guid> NxIntegrationImport { get; set; }
        public string Code { get; set; }
        public Nullable<int> VoucherWestLawPayee { get; set; }
        public string VoucherWestLawCostType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BizTalkImportFileEvent> BizTalkImportFileEvents { get; set; }
        public virtual NxIntegrationImport NxIntegrationImport1 { get; set; }
    }
}
