//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class NxLogText
    {
        public System.Guid NxLogTextID { get; set; }
        public string Filename { get; set; }
        public byte immediateClose { get; set; }
        public byte appendToFile { get; set; }
        public byte immediateFlush { get; set; }
    }
}
