//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class NxNtfSchedTimeWeekly
    {
        public System.Guid NxNtfSchedTimeWeeklyID { get; set; }
        public Nullable<byte> Sunday { get; set; }
        public Nullable<byte> Monday { get; set; }
        public Nullable<byte> Tuesday { get; set; }
        public Nullable<byte> Wednesday { get; set; }
        public Nullable<byte> Thursday { get; set; }
        public Nullable<byte> Friday { get; set; }
        public Nullable<byte> Saturday { get; set; }
    }
}
