//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class NxNtfMsgDistribution
    {
        public System.Guid NxNtfMsgDistributionID { get; set; }
        public string Message { get; set; }
        public string Hash { get; set; }
        public Nullable<System.Guid> Task { get; set; }
        public Nullable<byte> Processed { get; set; }
        public Nullable<System.Guid> NxUser { get; set; }
        public Nullable<System.Guid> Event { get; set; }
        public string EmailAddress { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual NxFWKUser NxFWKUser { get; set; }
        public virtual NxNtfTask NxNtfTask { get; set; }
    }
}
