//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class NxOptionTimeSpan
    {
        public System.Guid NxOptionTimeSpanID { get; set; }
        public string SystemDefault { get; set; }
        public string MaxValue { get; set; }
        public string MinValue { get; set; }
    }
}
