//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class NxRptUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NxRptUnit()
        {
            this.NxRptUnitLines = new HashSet<NxRptUnitLine>();
        }
    
        public System.Guid NxRptUnitID { get; set; }
        public string NxUnit { get; set; }
        public string RptFisStartMonthList { get; set; }
        public System.Guid FirstFiscalYear { get; set; }
        public string RptCurr { get; set; }
        public string RptCurrType { get; set; }
        public Nullable<byte> IsActive { get; set; }
        public string GLRptUnitList { get; set; }
        public Nullable<byte> DeleteRptHistory { get; set; }
        public Nullable<byte> PermanentDeleteRptHistory { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual UnitYear UnitYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NxRptUnitLine> NxRptUnitLines { get; set; }
    }
}
