//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class NxSession
    {
        public System.Guid SessionID { get; set; }
        public System.DateTime LogIn { get; set; }
        public string CultureInfo { get; set; }
        public string NavInfo { get; set; }
        public string ProxyUser { get; set; }
    }
}
