//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class NxSecurityAuditRule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NxSecurityAuditRule()
        {
            this.NxSecurityAuditBreaches = new HashSet<NxSecurityAuditBreach>();
            this.NxSecurityAuditChecks = new HashSet<NxSecurityAuditCheck>();
            this.NxSecurityAuditNotifies = new HashSet<NxSecurityAuditNotify>();
        }
    
        public System.Guid NxSecurityAuditRuleID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<byte> IsActive { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NxSecurityAuditBreach> NxSecurityAuditBreaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NxSecurityAuditCheck> NxSecurityAuditChecks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NxSecurityAuditNotify> NxSecurityAuditNotifies { get; set; }
    }
}
