//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class NxSecurityNode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NxSecurityNode()
        {
            this.NxSecurityNodeBetaAppRights = new HashSet<NxSecurityNodeBetaAppRight>();
            this.NxSecurityNodeEffDateRights = new HashSet<NxSecurityNodeEffDateRight>();
            this.NxSecurityNodeRights = new HashSet<NxSecurityNodeRight>();
            this.NxSecurityResources = new HashSet<NxSecurityResource>();
        }
    
        public System.Guid NxSecurityNodeID { get; set; }
        public string Caption { get; set; }
        public Nullable<System.Guid> ParentNode { get; set; }
        public Nullable<int> Ordinal { get; set; }
        public Nullable<int> Depth { get; set; }
        public Nullable<byte> HasChildren { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NxSecurityNodeBetaAppRight> NxSecurityNodeBetaAppRights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NxSecurityNodeEffDateRight> NxSecurityNodeEffDateRights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NxSecurityNodeRight> NxSecurityNodeRights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NxSecurityResource> NxSecurityResources { get; set; }
    }
}
