//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class NxSecurityStandardDataRole
    {
        public System.Guid NxSecurityStandardDataRoleID { get; set; }
        public string Description_UnformattedText { get; set; }
        public byte IsATMWhenTkprIsBillTkpr { get; set; }
        public byte IsATMWhenTkprIsRespTkpr { get; set; }
        public byte IsATMWhenTkprIsSupvTkpr { get; set; }
        public byte IsATMWhenTkprIsOrigTkpr { get; set; }
        public byte IsATMWhenTkprIsProlfTkpr { get; set; }
        public byte IsATMWhenTkprIsOpenTkpr { get; set; }
        public byte IsATMWhenTkprOffIsMattOffice { get; set; }
        public byte IsATMWhenTkprDeptIsMattDept { get; set; }
        public byte IsATMWhenTkprSecIsMattSec { get; set; }
        public byte IsATMWhenTkprIsOnMattTkprTeam { get; set; }
        public byte IsATCWhenTkprIsBillTkpr { get; set; }
        public byte IsATCWhenTkprIsRespTkpr { get; set; }
        public byte IsATCWhenTkprIsSupvTkpr { get; set; }
        public byte IsATCWhenTkprIsOrigTkpr { get; set; }
        public byte IsATCWhenTkprIsProlfTkpr { get; set; }
        public byte IsATCWhenTkprIsOpenTkpr { get; set; }
        public byte IsATCWhenTkprOffIsMattOffice { get; set; }
        public byte IsATCWhenTkprIsOnMattTkprTeam { get; set; }
        public byte IsApplyAccessToAllMappedTkpr { get; set; }
        public byte IsGrantConfPayee { get; set; }
        public Nullable<byte> IsGrantFullAdmin { get; set; }
        public Nullable<byte> IsGrantFullMatter { get; set; }
        public Nullable<byte> IsGrantFullClient { get; set; }
        public string MatterViewXOQL { get; set; }
        public string ClientViewXOQL { get; set; }
        public string PayeeViewXOQL { get; set; }
        public string Descr { get; set; }
    }
}
