//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class NxSimpleList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NxSimpleList()
        {
            this.NxAttachmentTargetOverrides = new HashSet<NxAttachmentTargetOverride>();
            this.NxAttachmentTargetSystemDefaults = new HashSet<NxAttachmentTargetSystemDefault>();
            this.NxFWKUsers = new HashSet<NxFWKUser>();
            this.NxWfConditions = new HashSet<NxWfCondition>();
            this.NxWfConditions1 = new HashSet<NxWfCondition>();
            this.NxWfConditions2 = new HashSet<NxWfCondition>();
            this.NxWfConditionSets = new HashSet<NxWfConditionSet>();
            this.NxWfEmailVariablesLists = new HashSet<NxWfEmailVariablesList>();
            this.NxWFReportDetails = new HashSet<NxWFReportDetail>();
            this.NxWfXOQLFilters = new HashSet<NxWfXOQLFilter>();
        }
    
        public System.Guid NxSimpleListID { get; set; }
        public string ListType { get; set; }
        public string Code { get; set; }
        public byte IsVisible { get; set; }
        public byte IsDeployable { get; set; }
        public string Description { get; set; }
        public byte IsDefault { get; set; }
        public byte IsStock { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NxAttachmentTargetOverride> NxAttachmentTargetOverrides { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NxAttachmentTargetSystemDefault> NxAttachmentTargetSystemDefaults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NxFWKUser> NxFWKUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NxWfCondition> NxWfConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NxWfCondition> NxWfConditions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NxWfCondition> NxWfConditions2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NxWfConditionSet> NxWfConditionSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NxWfEmailVariablesList> NxWfEmailVariablesLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NxWFReportDetail> NxWFReportDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NxWfXOQLFilter> NxWfXOQLFilters { get; set; }
    }
}
