//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class NxWfXOQLFilter
    {
        public System.Guid NxWfXOQLFilterID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string NxWfXOQLFilterType { get; set; }
        public string XOQLString { get; set; }
        public string SQLString { get; set; }
        public Nullable<byte> IsValidated { get; set; }
        public string DataType { get; set; }
        public Nullable<byte> IsPct { get; set; }
        public Nullable<byte> IsString { get; set; }
        public Nullable<byte> IsNumber { get; set; }
        public Nullable<byte> IsGUID { get; set; }
        public string OQLString { get; set; }
        public Nullable<System.Guid> XOQLReturnDataType { get; set; }
        public byte IsStock { get; set; }
        public byte IsDeployable { get; set; }
        public string Method { get; set; }
        public Nullable<System.Guid> NxFWKAppObject { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual NxFWKAppObject NxFWKAppObject1 { get; set; }
        public virtual NxSimpleList NxSimpleList { get; set; }
    }
}
