//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class NxWfConditionSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NxWfConditionSet()
        {
            this.NxWfConditions = new HashSet<NxWfCondition>();
        }
    
        public System.Guid NxWfConditionSetID { get; set; }
        public Nullable<System.Guid> NxWfRuleSet { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> LogicalOperator { get; set; }
        public Nullable<int> SortIndex { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual NxSimpleList NxSimpleList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NxWfCondition> NxWfConditions { get; set; }
        public virtual NxWfRuleSet NxWfRuleSet1 { get; set; }
    }
}
