//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        public System.Guid OfficeID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string NxUnit { get; set; }
        public System.Guid GLOffice { get; set; }
        public Nullable<int> Site { get; set; }
        public string NextInvNumber { get; set; }
        public string NextCrNoteNumber { get; set; }
        public string NextTaxInvNumber { get; set; }
        public int PriorityEntryType { get; set; }
        public int PriorityMatter { get; set; }
        public int PriorityBillingGroup { get; set; }
        public int PriorityOffice { get; set; }
        public string OfficeGroup { get; set; }
        public Nullable<int> DueDays { get; set; }
        public string IDMaskIdentifier { get; set; }
        public Nullable<System.Guid> ProfDCSTemplate { get; set; }
        public Nullable<System.Guid> BillDCSTemplate { get; set; }
        public Nullable<System.Guid> StmtDCSTemplate { get; set; }
        public string CKPrimarySort { get; set; }
        public string CKSecondarySort { get; set; }
        public string CKPrimarySortOrder { get; set; }
        public string CKSecondarySortOrder { get; set; }
        public string NextRcptNumber { get; set; }
        public string NextVoucherNumber { get; set; }
        public string NextGJNumber { get; set; }
        public string NextCashTranNumber { get; set; }
        public string TaxArea { get; set; }
        public string TaxInfo1 { get; set; }
        public string TaxInfo2 { get; set; }
        public string NextCRTaxInvNUmber { get; set; }
        public string NextPONumber { get; set; }
        public string WestLawAcctNum { get; set; }
        public string NextTrustRcptNumber { get; set; }
        public string NextControlledMoneyNumber { get; set; }
        public string NextTrustAdjNumber { get; set; }
        public string NextTrustEFTNumber { get; set; }
        public Nullable<System.Guid> CreditNoteDCSTemplate { get; set; }
        public Nullable<System.Guid> BillGroupDCSTemplate { get; set; }
        public Nullable<System.Guid> CreditNoteGroupDCSTemplate { get; set; }
    
        public virtual GLOffice GLOffice1 { get; set; }
        public virtual NxPrinterTemplate NxPrinterTemplate { get; set; }
        public virtual NxPrinterTemplate NxPrinterTemplate1 { get; set; }
        public virtual NxPrinterTemplate NxPrinterTemplate2 { get; set; }
        public virtual NxPrinterTemplate NxPrinterTemplate3 { get; set; }
        public virtual NxPrinterTemplate NxPrinterTemplate4 { get; set; }
        public virtual NxPrinterTemplate NxPrinterTemplate5 { get; set; }
    }
}
