//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class PODetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PODetail()
        {
            this.POPosts = new HashSet<POPost>();
            this.POReceipts = new HashSet<POReceipt>();
            this.VchrDetails = new HashSet<VchrDetail>();
        }
    
        public System.Guid PODetailID { get; set; }
        public int PO { get; set; }
        public System.DateTime DateRequired { get; set; }
        public Nullable<System.DateTime> InitialShipDate { get; set; }
        public Nullable<System.DateTime> ExpectedShipDate { get; set; }
        public int QntOrder { get; set; }
        public string ProductCode { get; set; }
        public string Description { get; set; }
        public string Currency { get; set; }
        public decimal UnitCost { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<int> Matter { get; set; }
        public Nullable<int> ExpenseGLAcct { get; set; }
        public byte IsEncumb { get; set; }
        public string EncumbMap { get; set; }
        public string Comments { get; set; }
        public Nullable<decimal> QntRcpt { get; set; }
        public Nullable<decimal> QntInvHold { get; set; }
        public int LineNum { get; set; }
        public string UOM { get; set; }
        public string Project { get; set; }
        public string Office { get; set; }
        public Nullable<int> Timekeeper { get; set; }
        public System.Guid RequestNxUser { get; set; }
        public Nullable<decimal> QntInvApp { get; set; }
        public Nullable<decimal> QntInsp { get; set; }
        public byte IsClosed { get; set; }
        public byte IsRush { get; set; }
        public System.Guid DeliverNxUser { get; set; }
        public Nullable<System.Guid> POReqDetail { get; set; }
        public Nullable<System.Guid> FAClassType { get; set; }
        public string FACategory { get; set; }
        public string TaxCode { get; set; }
        public Nullable<decimal> QntReq { get; set; }
        public string Category { get; set; }
        public byte IsActive { get; set; }
        public string CostType { get; set; }
        public Nullable<System.DateTime> CurrDate { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<System.DateTime> GLDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<System.Guid> OrigPODetail { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual FAClassType FAClassType1 { get; set; }
        public virtual NxUser NxUser { get; set; }
        public virtual NxUser NxUser1 { get; set; }
        public virtual POReqDetail POReqDetail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POPost> POPosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POReceipt> POReceipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VchrDetail> VchrDetails { get; set; }
    }
}
