//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostMsgQueue
    {
        public System.Guid PostMsgQueueID { get; set; }
        public int PostMessageQueueIndex { get; set; }
        public System.DateTime TimeCreated { get; set; }
        public Nullable<System.DateTime> TimeProcessed { get; set; }
        public Nullable<int> TimeCard { get; set; }
        public Nullable<int> CostCard { get; set; }
        public Nullable<int> ChrgCard { get; set; }
        public Nullable<int> ARMaster { get; set; }
        public Nullable<int> RcptMaster { get; set; }
        public Nullable<int> PostIndex { get; set; }
        public string PostSource { get; set; }
        public Nullable<int> ReversedIndex { get; set; }
        public string PostMgrStatusList { get; set; }
        public string FailedMessage { get; set; }
        public System.Guid NxUser { get; set; }
        public Nullable<System.DateTime> GLDate { get; set; }
        public Nullable<System.Guid> PostGuid { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual NxUser NxUser1 { get; set; }
    }
}
