//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrftWeightingAllocationMethod
    {
        public System.Guid PrftWeightingAllocationMethodID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte IsUnitWeighted { get; set; }
        public byte IsOfficeWeighted { get; set; }
        public byte IsDepartmentWeighted { get; set; }
        public byte IsSectionWeighted { get; set; }
        public byte IsTitleWeighted { get; set; }
        public byte IsTimekeeperWeighted { get; set; }
        public byte IsHeadcountCalcOnTheFly { get; set; }
        public string PrftHeadcountList { get; set; }
        public byte IsExpenseDimensionsUsed { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
