//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrftExternalExpenseCategory
    {
        public System.Guid PrftExternalExpenseCategoryID { get; set; }
        public string ExternalSource { get; set; }
        public string FirstExpenseType { get; set; }
        public string SecondExpenseType { get; set; }
        public string ThirdExpenseType { get; set; }
        public string FourthExpenseType { get; set; }
        public string FifthExpenseType { get; set; }
        public string SixthExpenseType { get; set; }
    }
}
