//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCode
    {
        public System.Guid ProductCodeID { get; set; }
        public string Code { get; set; }
        public Nullable<int> MinQnt { get; set; }
        public Nullable<int> MaxQnt { get; set; }
        public Nullable<int> GLAcctMask { get; set; }
        public string Office { get; set; }
        public string Description { get; set; }
        public string ProductType { get; set; }
        public string UOM { get; set; }
        public byte IsService { get; set; }
        public string TimeType { get; set; }
        public string CostType { get; set; }
        public string ChrgType { get; set; }
        public Nullable<System.Guid> FACLassType { get; set; }
        public string Category { get; set; }
        public string FACategory { get; set; }
        public string Manufacturer { get; set; }
        public string ModelNum { get; set; }
    
        public virtual FAClassType FAClassType1 { get; set; }
    }
}
