//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfMasterTax
    {
        public System.Guid ProfMasterTaxID { get; set; }
        public int ProfTaxIndex { get; set; }
        public int ProfMaster { get; set; }
        public string ProfDetailArchetype { get; set; }
        public Nullable<int> ProfDetIndex { get; set; }
        public int Payor { get; set; }
        public string Layer { get; set; }
        public string ForAttentionOf { get; set; }
        public string RefNumber { get; set; }
        public byte IsDefaultPayor { get; set; }
        public byte IsDefaultLayer { get; set; }
        public string TaxCode { get; set; }
        public string Tax { get; set; }
        public decimal TaxRate { get; set; }
        public decimal TaxAmt { get; set; }
        public string Currency { get; set; }
        public System.DateTime CurrDate { get; set; }
        public string TransactionType { get; set; }
        public System.DateTime WorkDate { get; set; }
        public decimal SourceAmt { get; set; }
        public byte IsHardCost { get; set; }
        public string ChrgCatList { get; set; }
        public byte IsCreditNote { get; set; }
        public byte IsWorkDateUsed { get; set; }
        public byte IsTaxOnTax { get; set; }
        public byte IsAdjustment { get; set; }
        public Nullable<int> TimeCard { get; set; }
        public Nullable<int> CostCard { get; set; }
        public Nullable<int> ChrgCard { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string TaxCodeDescription { get; set; }
    }
}
