//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfGroup()
        {
            this.ProfGroupMatters = new HashSet<ProfGroupMatter>();
        }
    
        public System.Guid ProfGroupID { get; set; }
        public string BillingGroup { get; set; }
        public System.DateTime ProfDate { get; set; }
        public Nullable<int> InvMaster { get; set; }
        public string InvNumber { get; set; }
        public string CrNoteNumber { get; set; }
        public string TaxInvNumber { get; set; }
        public Nullable<System.DateTime> InvDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> ProfMaster { get; set; }
        public string Office { get; set; }
        public Nullable<System.Guid> ProfDCSTemplate { get; set; }
        public Nullable<System.Guid> BillDCSTemplate { get; set; }
        public string FromTaxArea { get; set; }
        public string ToTaxArea { get; set; }
        public Nullable<System.Guid> ProfGenerationRun { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public string TaxReportID1 { get; set; }
        public string TaxReportID2 { get; set; }
        public string Description { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public byte IsFullCreditNote { get; set; }
        public Nullable<int> PrevInvMaster { get; set; }
    
        public virtual NxPrinterTemplate NxPrinterTemplate { get; set; }
        public virtual NxPrinterTemplate NxPrinterTemplate1 { get; set; }
        public virtual ProfGenerationRun ProfGenerationRun1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfGroupMatter> ProfGroupMatters { get; set; }
    }
}
