//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptTypeAdditionalPost
    {
        public System.Guid ReceiptTypeAdditionalPostID { get; set; }
        public string ReceiptType { get; set; }
        public string NxUnit { get; set; }
        public string GLType { get; set; }
        public int DebitMask { get; set; }
        public int CreditMask { get; set; }
        public string UnitPostDriverList { get; set; }
        public Nullable<decimal> PostingFraction { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<System.Guid> AnchorMask { get; set; }
    
        public virtual BaseGLSegment BaseGLSegment { get; set; }
    }
}
