//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedEntity
    {
        public System.Guid RelatedEntityID { get; set; }
        public int Relate { get; set; }
        public int Entity { get; set; }
        public Nullable<System.Guid> RelTypeDescription { get; set; }
        public Nullable<int> InvEntity { get; set; }
        public byte IsSubject { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual RelTypeDescription RelTypeDescription1 { get; set; }
    }
}
