//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevalGrpLine
    {
        public System.Guid RevalGrpLineID { get; set; }
        public int LineNum { get; set; }
        public int RealGainMask { get; set; }
        public int UnRealGainMask { get; set; }
        public string RevalGrp { get; set; }
        public string LineName { get; set; }
        public int LineIndex { get; set; }
        public int GLAcct { get; set; }
        public int RealLossMask { get; set; }
        public int UnRealLossMask { get; set; }
        public string CurrType { get; set; }
        public byte RealizedFX { get; set; }
        public Nullable<int> UTFRealGainMask { get; set; }
        public Nullable<int> UTFUnrealGainMask { get; set; }
        public Nullable<int> UTFRealLossMask { get; set; }
        public Nullable<int> UTFUnrealLossMask { get; set; }
        public string RevalCurrGrp { get; set; }
    }
}
