//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReverseSplitEvent
    {
        public System.Guid ReverseSplitEventID { get; set; }
        public int ReverseSplitEventIndex { get; set; }
        public System.Guid UserID { get; set; }
        public string OperatingUnit { get; set; }
        public Nullable<int> AuthorizedBy { get; set; }
        public string Reason { get; set; }
    }
}
