//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMAppOptionString
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RMAppOptionString()
        {
            this.RMAppOptStrOffices = new HashSet<RMAppOptStrOffice>();
            this.RMAppOptStrRoles = new HashSet<RMAppOptStrRole>();
            this.RMAppOptStrUsers = new HashSet<RMAppOptStrUser>();
        }
    
        public System.Guid RMAppOptionStringID { get; set; }
        public string StringValue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RMAppOptStrOffice> RMAppOptStrOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RMAppOptStrRole> RMAppOptStrRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RMAppOptStrUser> RMAppOptStrUsers { get; set; }
    }
}
