//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMAppConfigValue
    {
        public System.Guid RMAppConfigValuesID { get; set; }
        public System.Guid RMAppConfig { get; set; }
        public string RMOptionList { get; set; }
        public string RMFileType { get; set; }
        public string RMContainerType { get; set; }
        public byte IsFirmValue { get; set; }
        public string Office { get; set; }
        public Nullable<System.Guid> NxRole { get; set; }
        public Nullable<System.Guid> NxUser { get; set; }
        public Nullable<int> IntegerValue { get; set; }
        public string StringValue { get; set; }
        public string ListValue { get; set; }
        public Nullable<System.Guid> RelationshipValue { get; set; }
        public Nullable<byte> BooleanValue1 { get; set; }
        public Nullable<byte> BooleanValue2 { get; set; }
        public string RMContainerTypeValue { get; set; }
        public Nullable<int> RMEntityValue { get; set; }
        public string OfficeValue { get; set; }
        public string RMFileStatusValue { get; set; }
        public string RMFilingStatusValue { get; set; }
        public string RMDeliveryTimeframeValue { get; set; }
        public string RMDeliveryMethodValue { get; set; }
        public Nullable<System.Guid> NxPrinterTemplateValue { get; set; }
        public string NxPrinterValue { get; set; }
        public string RMCategoryValue { get; set; }
        public string RMLocationValue { get; set; }
        public string RMMediaTypeValue { get; set; }
        public string RMPrintLabelListValue { get; set; }
        public Nullable<System.Guid> NxBaseUserValue { get; set; }
        public string EntityTypeValue { get; set; }
        public string MattStatusValue { get; set; }
        public string CliStatusTypeValue { get; set; }
        public Nullable<int> MatterValue { get; set; }
        public string CftSearchReasonValue { get; set; }
        public string CftSearchResultsViewListValue { get; set; }
        public string CmEvSendAsListValue { get; set; }
        public Nullable<System.Guid> CmTimeZoneValue { get; set; }
        public string CftSearchReportTypeListValue { get; set; }
        public string RMFileTypeValue { get; set; }
        public string CftSearchReportTemplateValue { get; set; }
        public Nullable<System.Guid> NxSyncMapValue { get; set; }
        public Nullable<System.Guid> NxSyncfieldValue { get; set; }
        public string CftSearchAuthorityListValue { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual NxBaseUser NxBaseUser { get; set; }
        public virtual NxPrinterTemplate NxPrinterTemplate { get; set; }
        public virtual NxRole NxRole1 { get; set; }
        public virtual NxSyncField NxSyncField { get; set; }
        public virtual NxSyncMap NxSyncMap { get; set; }
        public virtual NxUser NxUser1 { get; set; }
        public virtual RMAppConfig RMAppConfig1 { get; set; }
    }
}
