//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMAppOption
    {
        public System.Guid RMAppOptionID { get; set; }
        public System.Guid RMAppConfig { get; set; }
        public string RMOptionList { get; set; }
        public string SystemDefault { get; set; }
        public string FirmOverride { get; set; }
        public string OfficeOverride { get; set; }
        public string RoleOverride { get; set; }
        public string UserOverride { get; set; }
        public string Office { get; set; }
        public Nullable<System.Guid> NxRole { get; set; }
        public Nullable<System.Guid> NxUser { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual NxRole NxRole1 { get; set; }
        public virtual NxUser NxUser1 { get; set; }
        public virtual RMAppConfig RMAppConfig1 { get; set; }
    }
}
