//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMDispProjectFile
    {
        public System.Guid RMDispProjectFilesID { get; set; }
        public Nullable<int> RMDispProject { get; set; }
        public int RMBaseFile { get; set; }
        public byte IsApproved { get; set; }
        public Nullable<System.Guid> NxUserApprover { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.Guid NxUserAdded { get; set; }
        public string Comment { get; set; }
        public Nullable<System.Guid> RMDispPhase { get; set; }
        public string FileIndexSortString { get; set; }
        public Nullable<int> Parent { get; set; }
        public int RMDispProjectFilesIndex { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual NxUser NxUser { get; set; }
        public virtual NxUser NxUser1 { get; set; }
        public virtual RMDispPhase RMDispPhase1 { get; set; }
    }
}
