//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMGMCtr
    {
        public System.Guid RMGMCtrsID { get; set; }
        public int GMCtrsIndex { get; set; }
        public string DescrCurrValue { get; set; }
        public string DescrNewValue { get; set; }
        public string DescrRMGMOptList { get; set; }
        public string NarrCurrValue { get; set; }
        public string NarrNewValue { get; set; }
        public string NarrRMGMOptList { get; set; }
        public string RMFilingStatus { get; set; }
        public string RecordOffice { get; set; }
        public string RMContainer { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
    }
}
