//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMMisfileInvContent
    {
        public System.Guid RMMisfileInvContentsID { get; set; }
        public int MisfileInvContentsIndex { get; set; }
        public Nullable<int> RMInventory { get; set; }
        public int RMBaseFile { get; set; }
        public string Status { get; set; }
        public Nullable<int> FoundInRMBaseFile { get; set; }
        public System.DateTime DateTimeScanned { get; set; }
        public string RMAccessLvlList { get; set; }
        public Nullable<int> PreviousCirculateToPerson { get; set; }
        public string PreviousFilingLocation { get; set; }
        public Nullable<int> PreviousContainer { get; set; }
        public Nullable<int> EWClient { get; set; }
        public Nullable<int> EWMatter { get; set; }
        public string PreviousCurrentLocation { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
