//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMRTCHistory
    {
        public System.Guid RMRTCHistoryID { get; set; }
        public string RMRTCDecisionList { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public Nullable<System.Guid> Nxuser { get; set; }
        public Nullable<int> RMRequestToCreate { get; set; }
        public string Comment { get; set; }
        public string Comment_UnformattedText { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual NxUser NxUser1 { get; set; }
    }
}
