//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMTrust
    {
        public System.Guid RMTrustsID { get; set; }
        public int TrustsIndex { get; set; }
        public Nullable<System.DateTime> TrustDate { get; set; }
        public string TrustName { get; set; }
        public Nullable<int> EntitySettlor { get; set; }
        public Nullable<int> EntityLifeTenant { get; set; }
        public Nullable<int> NumPkts { get; set; }
        public string Comments { get; set; }
        public string Comments_UnformattedText { get; set; }
    }
}
