//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityLabel
    {
        public System.Guid SecurityLabelID { get; set; }
        public int LabelIndex { get; set; }
        public string LabelXml { get; set; }
        public string LabelHash { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
