//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxCodeDate
    {
        public System.Guid TaxCodeDateID { get; set; }
        public string TaxCodeLkUp { get; set; }
        public System.DateTime EffDate { get; set; }
        public decimal BillDisplayTaxRate { get; set; }
        public Nullable<System.DateTime> NxEndDate { get; set; }
        public Nullable<System.DateTime> NxStartDate { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
