//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempMatterLoad
    {
        public string Number { get; set; }
        public string AltNumber { get; set; }
        public string DisplayName { get; set; }
        public int Client { get; set; }
        public string MattInfo { get; set; }
        public string MattType { get; set; }
        public string MattCategory { get; set; }
        public string MattStatus { get; set; }
        public Nullable<System.DateTime> MattStatusDate { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public int Language { get; set; }
        public string ReferralInfo { get; set; }
        public string ContactInfo { get; set; }
        public string MattCloseType { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public byte IsMaster { get; set; }
        public byte IsProBono { get; set; }
        public byte IsAdmin { get; set; }
        public Nullable<byte> IsNonBillable { get; set; }
        public int OpenTkpr { get; set; }
        public Nullable<byte> IsDefault { get; set; }
        public byte IsNoProforma { get; set; }
        public byte IsNoBill { get; set; }
        public string TimeTaxCode { get; set; }
        public string CostTaxCode { get; set; }
        public string ChrgTaxCode { get; set; }
        public string Currency { get; set; }
        public string CurrencyDateList { get; set; }
        public byte IsEngageLetterReq { get; set; }
        public byte IsWaiverLetterReq { get; set; }
        public Nullable<byte> IsConflictsConfidential { get; set; }
        public string VATRegistration { get; set; }
        public Nullable<byte> IsForeign { get; set; }
        public byte IsEBill { get; set; }
        public byte IsFeeEstimate { get; set; }
        public byte IsICBAcctRec { get; set; }
        public byte IsICBPayable { get; set; }
        public byte IsAllowTrustOverdraw { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string BillingOffice { get; set; }
        public byte IsLeadVolumeDiscountMatter { get; set; }
        public byte IsBillStatementIncludeDoubtful { get; set; }
        public string Comments { get; set; }
        public string Description { get; set; }
        public string BillingInstruc { get; set; }
        public string WaiverLetterComment { get; set; }
        public Nullable<System.DateTime> WaiverLetterSubDate { get; set; }
        public string EngageLetterComment { get; set; }
    }
}
