//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class TERebuildAllIndexes_DetailLog
    {
        public System.Guid TERebuildAllIndexes_DetailLogID { get; set; }
        public int Detail_Log_ID { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> Collection_Date { get; set; }
        public string Description { get; set; }
    }
}
