//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTypeDateRate
    {
        public System.Guid TimeTypeDateRateID { get; set; }
        public decimal FromQuantity { get; set; }
        public decimal Rate { get; set; }
        public decimal CarryOverAmt { get; set; }
        public string Currency { get; set; }
        public System.DateTime CurrDate { get; set; }
        public Nullable<System.Guid> TimeTypeDate { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual TimeTypeDate TimeTypeDate1 { get; set; }
    }
}
