//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeCardPostFailure
    {
        public System.Guid TimeCardPostFailureID { get; set; }
        public byte IsNB { get; set; }
        public byte IsNoCharge { get; set; }
        public Nullable<System.DateTime> WorkDate { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> WorkHrs { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public string TimeInterval { get; set; }
        public string WorkType { get; set; }
        public string TimeType { get; set; }
        public string TimeTypeAlias { get; set; }
        public string EntryUnitType { get; set; }
        public Nullable<int> EntryUnit { get; set; }
        public Nullable<int> Timekeeper { get; set; }
        public string TimekeeperAlias { get; set; }
        public string Office { get; set; }
        public Nullable<int> Matter { get; set; }
        public string MatterAlias { get; set; }
        public Nullable<int> Language { get; set; }
        public string TaxCode { get; set; }
        public string TaxJurisdiction { get; set; }
        public Nullable<System.Guid> Phase { get; set; }
        public string PhaseAlias { get; set; }
        public Nullable<System.Guid> Task { get; set; }
        public string TaskAlias { get; set; }
        public Nullable<System.Guid> Activity { get; set; }
        public string ActivityAlias { get; set; }
        public string Narrative { get; set; }
        public string Narrative_UnformattedText { get; set; }
        public string InternalComments { get; set; }
        public System.Guid BatchID { get; set; }
        public Nullable<System.Guid> RoleResponsible { get; set; }
        public string LoadNumber { get; set; }
        public string LoadSource { get; set; }
        public string LoadGroup { get; set; }
        public Nullable<int> SpvTimekeeper { get; set; }
        public string SpvTimekeeperAlias { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<System.Guid> Phase2 { get; set; }
        public Nullable<System.Guid> Task2 { get; set; }
        public Nullable<System.Guid> Activity2 { get; set; }
        public string Phase2Alias { get; set; }
        public string Task2Alias { get; set; }
        public string Activity2Alias { get; set; }
    }
}
