//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class tre_ruleset
    {
        public System.Guid tre_rulesetID { get; set; }
        public System.Guid iruleset { get; set; }
        public string code { get; set; }
        public string description { get; set; }
        public Nullable<System.Guid> icourtsystem { get; set; }
        public Nullable<System.Guid> itimezone { get; set; }
        public string cat_show_ruleset { get; set; }
        public Nullable<System.Guid> parent_index { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
