//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrustTransfer
    {
        public System.Guid TrustTransferID { get; set; }
        public int TrustTrsfIndex { get; set; }
        public System.DateTime TranDate { get; set; }
        public System.DateTime PostDate { get; set; }
        public Nullable<System.DateTime> GLDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> CurrDate { get; set; }
        public string TrustTransferType { get; set; }
        public string DocumentNumber { get; set; }
        public string Narrative { get; set; }
        public string Narrative_UnformattedText { get; set; }
        public byte IsReversed { get; set; }
        public Nullable<byte> IsReverseJournal { get; set; }
        public Nullable<System.DateTime> ReverseDate { get; set; }
        public string ReverseReason { get; set; }
        public Nullable<int> ReverseTransfer { get; set; }
        public string ReconStatusList { get; set; }
        public string AuthorizedBy { get; set; }
        public Nullable<System.DateTime> ClearDate { get; set; }
        public Nullable<int> ClearDays { get; set; }
        public Nullable<System.DateTime> MaturityDate { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string ConvNumber { get; set; }
        public string ConvSource { get; set; }
        public string ConvGroup { get; set; }
    }
}
