//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrustTransferPost
    {
        public System.Guid TrustTransferPostID { get; set; }
        public Nullable<int> TrustTransferDet { get; set; }
        public int TrustTransferPostHeader { get; set; }
    }
}
