//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnalType
    {
        public System.Guid UnalTypeID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public byte IsAutoFee { get; set; }
        public byte IsAutoHCost { get; set; }
        public byte IsAutoSCost { get; set; }
        public byte IsAutoBOA { get; set; }
        public byte IsAutoTax { get; set; }
        public byte IsAutoInt { get; set; }
        public byte IsAutoOthr { get; set; }
        public byte IsRemaskReversal { get; set; }
        public Nullable<System.DateTime> RemaskGLDate { get; set; }
        public byte IsReqUnallDetail { get; set; }
    }
}
