//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnArchiveDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnArchiveDetail()
        {
            this.ArchivedInvoices = new HashSet<ArchivedInvoice>();
        }
    
        public System.Guid UnArchiveDetailID { get; set; }
        public string ReqInvoices { get; set; }
        public Nullable<System.DateTime> ArchiveDate { get; set; }
        public string SelectedInvoices { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchivedInvoice> ArchivedInvoices { get; set; }
    }
}
