//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class VchrStatu
    {
        public System.Guid VchrStatusID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public byte IsAuthorized { get; set; }
        public byte IsAvailPymt { get; set; }
        public byte IsHoldClientPay { get; set; }
    }
}
