//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class VchrPost
    {
        public System.Guid VchrPostID { get; set; }
        public int Voucher { get; set; }
        public Nullable<System.Guid> VchrDetail { get; set; }
        public Nullable<System.Guid> DetailID { get; set; }
    
        public virtual VchrDetail VchrDetail1 { get; set; }
    }
}
