//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class VchrWHTDetail
    {
        public System.Guid VchrWHTDetailID { get; set; }
        public int Voucher { get; set; }
        public System.Guid VchrWHT { get; set; }
        public System.Guid DetailID { get; set; }
        public Nullable<System.Guid> VchrDetailID { get; set; }
        public string WHTaxCode { get; set; }
        public string Currency { get; set; }
        public System.DateTime CurrDate { get; set; }
        public decimal TaxAmt { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<System.Guid> OrigVchrDetailID { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string WHTaxReason { get; set; }
    }
}
