//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolumeDiscountGroupDateDet
    {
        public System.Guid VolumeDiscountGroupDateDetID { get; set; }
        public System.Guid VolumeDiscountGroupDate { get; set; }
        public string Currency { get; set; }
        public decimal TierAmount { get; set; }
        public System.DateTime EffStart { get; set; }
        public string TierHours { get; set; }
        public decimal DiscountPercent { get; set; }
        public string Instructions { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual VolumeDiscountGroupDate VolumeDiscountGroupDate1 { get; set; }
    }
}
