//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolumeDiscountGroupAccrualEvent
    {
        public System.Guid VolumeDiscountGroupAccrualEventID { get; set; }
        public string OperatingUnit { get; set; }
        public System.DateTime AsOfDate { get; set; }
        public System.DateTime InvDate { get; set; }
        public byte IsClosing { get; set; }
        public string ReqVolDiscGroups { get; set; }
        public string CurrType { get; set; }
        public string ProfStatus { get; set; }
        public System.Guid UserID { get; set; }
    }
}
