//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KischEbilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPMerge
    {
        public System.Guid VPMergeID { get; set; }
        public int RunIndex { get; set; }
        public System.DateTime RunDateTime { get; set; }
        public System.Guid RunUser { get; set; }
        public byte IsVendorMerge { get; set; }
        public Nullable<int> VendorFrom { get; set; }
        public Nullable<int> VendorTo { get; set; }
        public byte IsPayeeRenum { get; set; }
        public string Comments { get; set; }
        public string ArchetypeCode { get; set; }
        public Nullable<System.Guid> CurrProcItemID { get; set; }
        public Nullable<System.Guid> LastProcItemID { get; set; }
        public Nullable<System.Guid> OrigProcItemID { get; set; }
        public Nullable<byte> HasAttachments { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual NxUser NxUser { get; set; }
    }
}
